import Foundation

// Auto generated by write_ffmpeg_muxers.pl

// DO NOT EDIT BY HAND
// DO NOT EDIT BY HAND
// DO NOT EDIT BY HAND

public enum FFmpegMuxer: String, CaseIterable, Codable, Sendable {
    case vidc
    case flv
    case au
    case rtp_mpegts
    case sap
    case avm2
    case amv
    case webm
    case mpeg2video
    case gif
    case u8
    case fits
    case ttml
    case segment
    case ilbc
    case svcd
    case ffmetadata
    case srt
    case wav
    case mov
    case asf
    case alp
    case dfpwm
    case _3g2 = "3g2"
    case ipod
    case dts
    case rtp
    case hash
    case ismv
    case data
    case rawvideo
    case bit
    case film_cpk
    case image2
    case mmf
    case s32le
    case aptx
    case audiotoolbox
    case ircam
    case u16be
    case md5
    case mpjpeg
    case mxf
    case ast
    case webp
    case h263
    case s8
    case webvtt
    case g726
    case smoothstreaming
    case fifo
    case avi
    case cavsvideo
    case dv
    case u24be
    case hevc
    case framehash
    case null
    case ass
    case mjpeg
    case filmstrip
    case ico
    case avs2
    case rm
    case sup
    case s24be
    case asf_stream
    case ogg
    case u32le
    case amr
    case s24le
    case mp2
    case eac3
    case apm
    case scc
    case vcd
    case avs3
    case apng
    case adts
    case h264
    case mxf_opatom
    case framemd5
    case dash
    case mulaw
    case mlp
    case image2pipe
    case nut
    case oga
    case s16be
    case argo_cvg
    case s16le
    case rso
    case aptx_hd
    case spx
    case dvd
    case sox
    case ac3
    case wtv
    case f32le
    case psp
    case g722
    case avif
    case mpeg1video
    case flac
    case s32be
    case mp3
    case ogv
    case argo_asf
    case microdvd
    case obu
    case webm_chunk
    case f64le
    case wsaud
    case dnxhd
    case u16le
    case f32be
    case daud
    case g723_1
    case framecrc
    case a64
    case adx
    case spdif
    case yuv4mpegpipe
    case streamhash
    case hls
    case mkvtimestamp_v2
    case mp4
    case mpegts
    case rtsp
    case lrc
    case opus
    case alaw
    case webm_dash_manifest
    case codec2raw
    case mpeg
    case oma
    case hds
    case ivf
    case sbc
    case m4v
    case w64
    case uncodedframecrc
    case latm
    case mxf_d10
    case caf
    case swf
    case jacosub
    case u32be
    case roq
    case fifo_test
    case matroska
    case vc1test
    case aiff
    case gxf
    case dirac
    case wv
    case vob
    case kvag
    case f64be
    case codec2
    case smjpeg
    case vc1
    case h261
    case gsm
    case f4v
    case u24le
    case voc
    case g726le
    case truehd
    case crc
    case tta
    case tee
    case _3gp = "3gp"


    public var description: String {
        switch self {
        case .vidc:
            return "PCM Archimedes VIDC"
        case .flv:
            return "FLV (Flash Video)"
        case .au:
            return "Sun AU"
        case .rtp_mpegts:
            return "RTP/mpegts output format"
        case .sap:
            return "SAP output"
        case .avm2:
            return "SWF (ShockWave Flash) (AVM2)"
        case .amv:
            return "AMV"
        case .webm:
            return "WebM"
        case .mpeg2video:
            return "raw MPEG-2 video"
        case .gif:
            return "CompuServe Graphics Interchange Format (GIF)"
        case .u8:
            return "PCM unsigned 8-bit"
        case .fits:
            return "Flexible Image Transport System"
        case .ttml:
            return "TTML subtitle"
        case .segment:
            return "segment"
        case .ilbc:
            return "iLBC storage"
        case .svcd:
            return "MPEG-2 PS (SVCD)"
        case .ffmetadata:
            return "FFmpeg metadata in text"
        case .srt:
            return "SubRip subtitle"
        case .wav:
            return "WAV / WAVE (Waveform Audio)"
        case .mov:
            return "QuickTime / MOV"
        case .asf:
            return "ASF (Advanced / Active Streaming Format)"
        case .alp:
            return "LEGO Racers ALP"
        case .dfpwm:
            return "raw DFPWM1a"
        case ._3g2:
            return "3GP2 (3GPP2 file format)"
        case .ipod:
            return "iPod H.264 MP4 (MPEG-4 Part 14)"
        case .dts:
            return "raw DTS"
        case .rtp:
            return "RTP output"
        case .hash:
            return "Hash testing"
        case .ismv:
            return "ISMV/ISMA (Smooth Streaming)"
        case .data:
            return "raw data"
        case .rawvideo:
            return "raw video"
        case .bit:
            return "G.729 BIT file format"
        case .film_cpk:
            return "Sega FILM / CPK"
        case .image2:
            return "image2 sequence"
        case .mmf:
            return "Yamaha SMAF"
        case .s32le:
            return "PCM signed 32-bit little-endian"
        case .aptx:
            return "raw aptX (Audio Processing Technology for Bluetooth)"
        case .audiotoolbox:
            return "AudioToolbox output device"
        case .ircam:
            return "Berkeley/IRCAM/CARL Sound Format"
        case .u16be:
            return "PCM unsigned 16-bit big-endian"
        case .md5:
            return "MD5 testing"
        case .mpjpeg:
            return "MIME multipart JPEG"
        case .mxf:
            return "MXF (Material eXchange Format)"
        case .ast:
            return "AST (Audio Stream)"
        case .webp:
            return "WebP"
        case .h263:
            return "raw H.263"
        case .s8:
            return "PCM signed 8-bit"
        case .webvtt:
            return "WebVTT subtitle"
        case .g726:
            return "raw big-endian G.726 (\"left-justified\")"
        case .smoothstreaming:
            return "Smooth Streaming Muxer"
        case .fifo:
            return "FIFO queue pseudo-muxer"
        case .avi:
            return "AVI (Audio Video Interleaved)"
        case .cavsvideo:
            return "raw Chinese AVS (Audio Video Standard) video"
        case .dv:
            return "DV (Digital Video)"
        case .u24be:
            return "PCM unsigned 24-bit big-endian"
        case .hevc:
            return "raw HEVC video"
        case .framehash:
            return "Per-frame hash testing"
        case .null:
            return "raw null video"
        case .ass:
            return "SSA (SubStation Alpha) subtitle"
        case .mjpeg:
            return "raw MJPEG video"
        case .filmstrip:
            return "Adobe Filmstrip"
        case .ico:
            return "Microsoft Windows ICO"
        case .avs2:
            return "raw AVS2-P2/IEEE1857.4 video"
        case .rm:
            return "RealMedia"
        case .sup:
            return "raw HDMV Presentation Graphic Stream subtitles"
        case .s24be:
            return "PCM signed 24-bit big-endian"
        case .asf_stream:
            return "ASF (Advanced / Active Streaming Format)"
        case .ogg:
            return "Ogg"
        case .u32le:
            return "PCM unsigned 32-bit little-endian"
        case .amr:
            return "3GPP AMR"
        case .s24le:
            return "PCM signed 24-bit little-endian"
        case .mp2:
            return "MP2 (MPEG audio layer 2)"
        case .eac3:
            return "raw E-AC-3"
        case .apm:
            return "Ubisoft Rayman 2 APM"
        case .scc:
            return "Scenarist Closed Captions"
        case .vcd:
            return "MPEG-1 Systems / MPEG program stream (VCD)"
        case .avs3:
            return "AVS3-P2/IEEE1857.10"
        case .apng:
            return "Animated Portable Network Graphics"
        case .adts:
            return "ADTS AAC (Advanced Audio Coding)"
        case .h264:
            return "raw H.264 video"
        case .mxf_opatom:
            return "MXF (Material eXchange Format) Operational Pattern Atom"
        case .framemd5:
            return "Per-frame MD5 testing"
        case .dash:
            return "DASH Muxer"
        case .mulaw:
            return "PCM mu-law"
        case .mlp:
            return "raw MLP"
        case .image2pipe:
            return "piped image2 sequence"
        case .nut:
            return "NUT"
        case .oga:
            return "Ogg Audio"
        case .s16be:
            return "PCM signed 16-bit big-endian"
        case .argo_cvg:
            return "Argonaut Games CVG"
        case .s16le:
            return "PCM signed 16-bit little-endian"
        case .rso:
            return "Lego Mindstorms RSO"
        case .aptx_hd:
            return "raw aptX HD (Audio Processing Technology for Bluetooth)"
        case .spx:
            return "Ogg Speex"
        case .dvd:
            return "MPEG-2 PS (DVD VOB)"
        case .sox:
            return "SoX native"
        case .ac3:
            return "raw AC-3"
        case .wtv:
            return "Windows Television (WTV)"
        case .f32le:
            return "PCM 32-bit floating-point little-endian"
        case .psp:
            return "PSP MP4 (MPEG-4 Part 14)"
        case .g722:
            return "raw G.722"
        case .avif:
            return "AVIF"
        case .mpeg1video:
            return "raw MPEG-1 video"
        case .flac:
            return "raw FLAC"
        case .s32be:
            return "PCM signed 32-bit big-endian"
        case .mp3:
            return "MP3 (MPEG audio layer 3)"
        case .ogv:
            return "Ogg Video"
        case .argo_asf:
            return "Argonaut Games ASF"
        case .microdvd:
            return "MicroDVD subtitle format"
        case .obu:
            return "AV1 low overhead OBU"
        case .webm_chunk:
            return "WebM Chunk Muxer"
        case .f64le:
            return "PCM 64-bit floating-point little-endian"
        case .wsaud:
            return "Westwood Studios audio"
        case .dnxhd:
            return "raw DNxHD (SMPTE VC-3)"
        case .u16le:
            return "PCM unsigned 16-bit little-endian"
        case .f32be:
            return "PCM 32-bit floating-point big-endian"
        case .daud:
            return "D-Cinema audio"
        case .g723_1:
            return "raw G.723.1"
        case .framecrc:
            return "framecrc testing"
        case .a64:
            return "a64 - video for Commodore 64"
        case .adx:
            return "CRI ADX"
        case .spdif:
            return "IEC 61937 (used on S/PDIF - IEC958)"
        case .yuv4mpegpipe:
            return "YUV4MPEG pipe"
        case .streamhash:
            return "Per-stream hash testing"
        case .hls:
            return "Apple HTTP Live Streaming"
        case .mkvtimestamp_v2:
            return "extract pts as timecode v2 format, as defined by mkvtoolnix"
        case .mp4:
            return "MP4 (MPEG-4 Part 14)"
        case .mpegts:
            return "MPEG-TS (MPEG-2 Transport Stream)"
        case .rtsp:
            return "RTSP output"
        case .lrc:
            return "LRC lyrics"
        case .opus:
            return "Ogg Opus"
        case .alaw:
            return "PCM A-law"
        case .webm_dash_manifest:
            return "WebM DASH Manifest"
        case .codec2raw:
            return "raw codec2 muxer"
        case .mpeg:
            return "MPEG-1 Systems / MPEG program stream"
        case .oma:
            return "Sony OpenMG audio"
        case .hds:
            return "HDS Muxer"
        case .ivf:
            return "On2 IVF"
        case .sbc:
            return "raw SBC"
        case .m4v:
            return "raw MPEG-4 video"
        case .w64:
            return "Sony Wave64"
        case .uncodedframecrc:
            return "uncoded framecrc testing"
        case .latm:
            return "LOAS/LATM"
        case .mxf_d10:
            return "MXF (Material eXchange Format) D-10 Mapping"
        case .caf:
            return "Apple CAF (Core Audio Format)"
        case .swf:
            return "SWF (ShockWave Flash)"
        case .jacosub:
            return "JACOsub subtitle format"
        case .u32be:
            return "PCM unsigned 32-bit big-endian"
        case .roq:
            return "raw id RoQ"
        case .fifo_test:
            return "Fifo test muxer"
        case .matroska:
            return "Matroska"
        case .vc1test:
            return "VC-1 test bitstream"
        case .aiff:
            return "Audio IFF"
        case .gxf:
            return "GXF (General eXchange Format)"
        case .dirac:
            return "raw Dirac"
        case .wv:
            return "raw WavPack"
        case .vob:
            return "MPEG-2 PS (VOB)"
        case .kvag:
            return "Simon & Schuster Interactive VAG"
        case .f64be:
            return "PCM 64-bit floating-point big-endian"
        case .codec2:
            return "codec2 .c2 muxer"
        case .smjpeg:
            return "Loki SDL MJPEG"
        case .vc1:
            return "raw VC-1 video"
        case .h261:
            return "raw H.261"
        case .gsm:
            return "raw GSM"
        case .f4v:
            return "F4V Adobe Flash Video"
        case .u24le:
            return "PCM unsigned 24-bit little-endian"
        case .voc:
            return "Creative Voice"
        case .g726le:
            return "raw little-endian G.726 (\"right-justified\")"
        case .truehd:
            return "raw TrueHD"
        case .crc:
            return "CRC testing"
        case .tta:
            return "TTA (True Audio)"
        case .tee:
            return "Multiple muxer tee"
        case ._3gp:
            return "3GP (3GPP file format)"
        }
    }

}
