import Foundation

// a classifier that has a name and can be instantiated
public protocol NamedOutlierGroupClassifier: OutlierGroupClassifier {

    init()
    
    var type: ClassifierType { get }
    
    var name: String { get }
}

public enum ClassifierType: Sendable {
    case tree(DecisionTreeParams)
    case forest(DecisionForestParams)
}

public struct DecisionTreeParams: Sendable {
    // this initializer needs to be here to be public,
    // the autogenerated one can't be public :(
    public init(name: String,
               inputSequences: [String],
               positiveTrainingSize: Int,
               negativeTrainingSize: Int,
               decisionTypes: [OutlierGroup.Feature],
               decisionSplitTypes: [DecisionSplitType],
               maxDepth: Int?,
               pruned: Bool)
    {
        self.name = name
        self.inputSequences = inputSequences
        self.positiveTrainingSize = positiveTrainingSize
        self.negativeTrainingSize = negativeTrainingSize
        self.decisionTypes = decisionTypes
        self.decisionSplitTypes = decisionSplitTypes
        self.maxDepth = maxDepth
        self.pruned = pruned
    }
    
    let name: String
    let inputSequences: [String]
    let positiveTrainingSize: Int
    let negativeTrainingSize: Int
    let decisionTypes: [OutlierGroup.Feature]
    let decisionSplitTypes: [DecisionSplitType]
    let maxDepth: Int?
    let pruned: Bool
}

public struct DecisionForestParams: Sendable {
    // this initializer needs to be here to be public,
    // the autogenerated one can't be public :(
    public init(name: String,
                treeCount: Int,
                treeNames: [String])
    {
        self.name = name
        self.treeCount = treeCount
        self.treeNames = treeNames
    }

    public let name: String
    public let treeCount: Int
    public let treeNames: [String]
}

