#!/usr/bin/perl

use strict;

my $dirname = shift;

# this script allows a user to visually identify airplanes / non airplanes / not sure
# by showing them the visual txt files generated by ntar.
# files are then moved in response to the user's choices.

my $airplane_dir = "/Users/brian/git/nighttime_timelapse_airplane_eraser/outlier_data/airplanes";
my $non_airplane_dir = "/Users/brian/git/nighttime_timelapse_airplane_eraser/outlier_data/non_airplanes";
my $maybe_airplane_dir = "/Users/brian/git/nighttime_timelapse_airplane_eraser/outlier_data/maybe_airplanes";

opendir my $dir, $dirname or die "cannot open source dir: $!\n";

foreach my $filename (readdir $dir) {
    if($filename =~ /[.]txt$/) {
	print "$filename\n";
	system("cat $dirname/$filename");
	my $done = 0;
	my $response;
	while(!$done) {
	    $response = <>;
	    chomp $response;
	    if($response eq 'n' || $response eq 'v') {
		print "move it to no airplane\n";
		system("mv $dirname/$filename $non_airplane_dir");
		$done = 1;
	    } elsif($response eq 'a') {
		print "move it to airplane\n";
 		system("mv $dirname/$filename $airplane_dir");
		$done = 1;
	    } elsif($response eq 'u' || $response eq 'f') {
		print "move it to unsure about airplane or not\n";
		system("mv $dirname/$filename $maybe_airplane_dir");
		$done = 1;
	    }
	}
	print "$response\n";
    }
}

