
# coding: utf-8
#platform :ios, '12.0'

# The following line is necessary to allow changes in dependent pods to show up
# without first having to do a full clean everytime.
#install! 'cocoapods', :disable_input_output_paths => true
# Still an open issue as of 7/10/2019:
# https://github.com/CocoaPods/CocoaPods/issues/8073
# https://openradar.appspot.com/41126633

target 'ntar_gui' do
  use_frameworks!

  pod 'ArgumentParser'
  pod 'ntar', :path => "../"
  
  # this gets rid of some localizability warnings on the pods xcode project
  post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
      config.build_settings['CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED'] = 'YES'
    end
  end
end
