/*
   auto generated by decision_tree_generator on 2023-02-26 23:51:41 +0000 in 3 seconds

   with test data consisting of:
     - 2 groups known to be paintable
     - 1 groups known to not be paintable

   from input data described by:
     - ../test/test_small_medium-ntar-v-0_2_0-outliers/config.json

*/

// DO NOT EDIT THIS FILE
// DO NOT EDIT THIS FILE
// DO NOT EDIT THIS FILE

@available(macOS 10.15, *)
public extension OutlierGroup {

    // define a computed property which decides the paintability 
    // of this OutlierGroup with a decision tree
    var shouldPaintFromDecisionTree: Bool {
        get async {
            if await self.decisionTreeValue(for: .size) < 133.0 {
                return false
            } else {
                return true
            }
        }
    }
}