/*
   auto generated by decision_tree_generator on 2023-02-28 14:07:34 +0000 in 4 seconds

   with test data consisting of:
     - 8 groups known to be paintable
     - 2 groups known to not be paintable

   from input data described by:
     - ../test/test_small_lots-ntar-v-0_2_0-outliers/config.json

*/

// DO NOT EDIT THIS FILE
// DO NOT EDIT THIS FILE
// DO NOT EDIT THIS FILE

public struct OutlierGroupDecisionTree_2f017d7c {
    public let sha256 = "4c5868bf4e9177b7062316706711f4993aba2fc7fc61cf40787c76022f017d7c"

    public let generationSecondsSince1970 = 1677593254.1199899

    public let inputSequences =
        [
            "../test/test_small_lots-ntar-v-0_2_0-outliers/config.json"
        ]
}

@available(macOS 10.15, *)
public extension OutlierGroup {

    // decide the paintability of this OutlierGroup with a decision tree
    var shouldPaintFromDecisionTree_2f017d7c: Bool {
        get async {
            if self.nonAsyncDecisionTreeValue(for: .width) < 32.0 {
                return false
            } else {
                return true
            }
        }
    }
}