#!/usr/bin/perl

use strict;

open (FH, "../external_binaries/bin/ffmpeg -pix_fmts 2>/dev/null |") || die "cannot read pix fmts: $!\n";

open OUT, ">Sources/StarCore/FFmpegPixelFormat.swift";

my $started = 0;

my $fmts = {};

while(<FH>) {
  $started = 1 if(/^-----$/);
  if($started && /^([I.])([O.])([H.])([P.])([B.])\s+(\w+)\s+(\w+)\s+(\w+)\s+([\w-]+)/) {
    my ($input,
	$output,
	$hardware_acclerated,
	$palleted,
	$bitstream,
	$name,
	$num_components,
	$bits_per_pixels,
	$bit_depths) = ($1 ne '.', $2 ne '.', $3 ne '.', $4 ne '.', $5 ne '.', $6, $7, $8, $9);

    if ($name =~ /^\s*\d/) {
      $fmts->{$name} = {input => $input,
			output => $output,
			hardware_acclerated => $hardware_acclerated,
			palleted => $palleted,
			bitstream => $bitstream,
			name => "_".$name,
			real_name => $name,
			num_components => $num_components,
			bits_per_pixels => $bits_per_pixels,
			bit_depths => $bit_depths};
    } else {
      $fmts->{$name} = {input => $input,
			output => $output,
			hardware_acclerated => $hardware_acclerated,
			palleted => $palleted,
			bitstream => $bitstream,
			name => $name,
			num_components => $num_components,
			bits_per_pixels => $bits_per_pixels,
			bit_depths => $bit_depths};
    }
  }
}

print OUT "import Foundation\n\n";

print OUT "// Auto generated by $0\n\n";
print OUT "// DO NOT EDIT BY HAND\n";
print OUT "// DO NOT EDIT BY HAND\n";
print OUT "// DO NOT EDIT BY HAND\n\n";

print OUT "enum FFmpegPixelFormat: String, CaseIterable, Codable, Sendable {\n";
foreach my $name (keys %$fmts) {
  if(exists $fmts->{$name}{real_name}) {
    print OUT "    case $fmts->{$name}{name} = \"$fmts->{$name}{real_name}\"\n";
  } else {
    print OUT "    case $name\n";
  }
}

print OUT "\n\n";

print OUT "    public var canInput: Bool {\n";
print OUT "        switch self {\n";
foreach my $name (keys %$fmts) {
  if (exists $fmts->{$name}{real_name}) {
    print OUT "        case .$fmts->{$name}{name}:\n";
  } else {
    print OUT "        case .$name:\n";
  }
  if ($fmts->{$name}{input} == 1) {
    print OUT "            true\n";
  } else {
    print OUT "            false\n";
  }
}
print OUT "        }\n";
print OUT "    }\n\n";


print OUT "    public var canOutput: Bool {\n";
print OUT "        switch self {\n";
foreach my $name (keys %$fmts) {
  if (exists $fmts->{$name}{real_name}) {
    print OUT "        case .$fmts->{$name}{name}:\n";
  } else {
    print OUT "        case .$name:\n";
  }
  if($fmts->{$name}{output} == 1) {
    print OUT "            true\n";
  } else {
    print OUT "            false\n";
  }
}
print OUT "        }\n";
print OUT "    }\n\n";

print OUT "    public var isHardwareAccelrated: Bool {\n";
print OUT "        switch self {\n";
foreach my $name (keys %$fmts) {
  if (exists $fmts->{$name}{real_name}) {
    print OUT "        case .$fmts->{$name}{name}:\n";
  } else {
    print OUT "        case .$name:\n";
  }
  if($fmts->{$name}{hardware_acclerated} == 1) {
    print OUT "            true\n";
  } else {
    print OUT "            false\n";
  }
}
print OUT "        }\n";
print OUT "    }\n\n";


print OUT "    public var isPalleted: Bool {\n";
print OUT "        switch self {\n";
foreach my $name (keys %$fmts) {
  if (exists $fmts->{$name}{real_name}) {
    print OUT "        case .$fmts->{$name}{name}:\n";
  } else {
    print OUT "        case .$name:\n";
  }
  if($fmts->{$name}{palleted} == 1) {
    print OUT "            true\n";
  } else {
    print OUT "            false\n";
  }
}
print OUT "        }\n";
print OUT "    }\n\n";


print OUT "    public var isBitstream: Bool {\n";
print OUT "        switch self {\n";
foreach my $name (keys %$fmts) {
  if (exists $fmts->{$name}{real_name}) {
    print OUT "        case .$fmts->{$name}{name}:\n";
  } else {
    print OUT "        case .$name:\n";
  }
  if($fmts->{$name}{bitstream} == 1) {
    print OUT "            true\n";
  } else {
    print OUT "            false\n";
  }
}
print OUT "        }\n";
print OUT "    }\n\n";

print OUT "    public var numberOfComponents: Int {\n";
print OUT "        switch self {\n";
foreach my $name (keys %$fmts) {
  if (exists $fmts->{$name}{real_name}) {
    print OUT "        case .$fmts->{$name}{name}:\n";
  } else {
    print OUT "        case .$name:\n";
  }
  print OUT "            $fmts->{$name}{num_components}\n";
}
print OUT "        }\n";
print OUT "    }\n\n";


print OUT "    public var bitsPerPixel: Int {\n";
print OUT "        switch self {\n";
foreach my $name (keys %$fmts) {
  if (exists $fmts->{$name}{real_name}) {
    print OUT "        case .$fmts->{$name}{name}:\n";
  } else {
    print OUT "        case .$name:\n";
  }
  print OUT "            $fmts->{$name}{bits_per_pixels}\n";
}
print OUT "        }\n";
print OUT "    }\n\n";


print OUT "    public var bitDepths: String {\n";
print OUT "        switch self {\n";
foreach my $name (keys %$fmts) {
  if (exists $fmts->{$name}{real_name}) {
    print OUT "        case .$fmts->{$name}{name}:\n";
  } else {
    print OUT "        case .$name:\n";
  }
  print OUT "            \"$fmts->{$name}{bit_depths}\"\n";
}
print OUT "        }\n";
print OUT "    }\n\n";



print OUT "    public static var inputOutputPixelFormats: [FFmpegPixelFormat] {\n";
print OUT "        self.allCases\n";
print OUT '          .filter { $0.canInput }'."\n";
print OUT '          .filter { $0.canOutput }'."\n";
print OUT "    }\n";


print OUT "}\n";
