#!/usr/bin/perl

use strict;

open (FH, "../external_binaries/bin/ffmpeg -muxers 2>/dev/null |") || die "cannot read pix fmts: $!\n";

open OUT, ">Sources/StarCore/FFmpegMuxer.swift";

my $started = 0;

my $muxers = {};

while(<FH>) {
  $started = 1 if(/^ --$/);
  if($started && /^\s+E\s+(\w+)\s+(.*)/) {
    my ($name, $description) = ($1, $2);

    if ($name =~ /^\s*\d/) {
      $muxers->{$name} = {name => "_".$name,
			real_name => $name,
			description => $description};
    } else {
      $muxers->{$name} = {name => $name,
			description => $description};
    }
  }
}

print OUT "import Foundation\n\n";

print OUT "// Auto generated by $0\n\n";
print OUT "// DO NOT EDIT BY HAND\n";
print OUT "// DO NOT EDIT BY HAND\n";
print OUT "// DO NOT EDIT BY HAND\n\n";

print OUT "public enum FFmpegMuxer: String, CaseIterable, Codable, Sendable {\n";
foreach my $name (keys %$muxers) {
  if(exists $muxers->{$name}{real_name}) {
    print OUT "    case $muxers->{$name}{name} = \"$muxers->{$name}{real_name}\"\n";
  } else {
    print OUT "    case $name\n";
  }
}

print OUT "\n\n";

print OUT "    public var description: String {\n";
print OUT "        switch self {\n";
foreach my $name (keys %$muxers) {
  if (exists $muxers->{$name}{real_name}) {
    print OUT "        case .$muxers->{$name}{name}:\n";
  } else {
    print OUT "        case .$name:\n";
  }
  my $value = $muxers->{$name}{description};
  $value =~ s/\"/\\\"/g;
  print OUT "            return \"$value\"\n";
}
print OUT "        }\n";
print OUT "    }\n\n";



print OUT "}\n";
