#!/usr/bin/perl

use strict;

open (FH, "../external_binaries/bin/ffmpeg -codecs 2>/dev/null |") || die "cannot read pix fmts: $!\n";

open OUT, ">Sources/StarCore/FFmpegCodec.swift";

my $started = 0;

my $codecs = {};

while(<FH>) { 
  $started = 1 if(/^\s*-------\s*$/);
  if($started && /^\s*([D.])([E.])([VASDT.])([I.])([L.])([S.])\s+(\w+)\s+(.*)$/) {
      
    my ($decoding,
	$encoding,
	$codec_type,
	$intra_frame_only,
	$lossy,
	$lossless,
	$name,
	$description) = ($1 ne '.', $2 ne '.', $3, $4 ne '.', $5 ne '.', $6, $7, $8);

    if ($name =~ /^\s*\d/) {
	$codecs->{$name} = {name => "_".$name,
			    real_name => $name,
			    decoding => $decoding,
			    encoding => $encoding,
			    codec_type => $codec_type,
			    intra_frame_only => $intra_frame_only,
			    lossy => $lossy,
			    lossless => $lossless,
			    description => $description};
    } else {
	$codecs->{$name} = {decoding => $decoding,
			    encoding => $encoding,
			    codec_type => $codec_type,
			    intra_frame_only => $intra_frame_only,
			    lossy => $lossy,
			    lossless => $lossless,
			    name => $name,
			    description => $description};
    }
  }
}
close FH;

print OUT "import Foundation\n\n";

print OUT "// Auto generated by $0\n\n";
print OUT "// DO NOT EDIT BY HAND\n";
print OUT "// DO NOT EDIT BY HAND\n";
print OUT "// DO NOT EDIT BY HAND\n\n";

print OUT "public enum FFmpegCodec: String, CaseIterable, Codable, Sendable {\n";
foreach my $name (keys %$codecs) {
  if(exists $codecs->{$name}{real_name}) {
    print OUT "    case $codecs->{$name}{name} = \"$codecs->{$name}{real_name}\"\n";
  } else {
    print OUT "    case $name\n";
  }
}

print OUT "\n\n";

print OUT "    public var canDecode: Bool {\n";
print OUT "        switch self {\n";
foreach my $name (keys %$codecs) {
  if (exists $codecs->{$name}{real_name}) {
    print OUT "        case .$codecs->{$name}{name}:\n";
  } else {
    print OUT "        case .$name:\n";
  }
  if ($codecs->{$name}{decoding} == 1) {
    print OUT "            true\n";
  } else {
    print OUT "            false\n";
  }
}
print OUT "        }\n";
print OUT "    }\n\n";


print OUT "    public var canEncode: Bool {\n";
print OUT "        switch self {\n";
foreach my $name (keys %$codecs) {
  if (exists $codecs->{$name}{real_name}) {
    print OUT "        case .$codecs->{$name}{name}:\n";
  } else {
    print OUT "        case .$name:\n";
  }
  if($codecs->{$name}{encoding} == 1) {
    print OUT "            true\n";
  } else {
    print OUT "            false\n";
  }
}
print OUT "        }\n";
print OUT "    }\n\n";

print OUT "    public var isIntraFrameOnly: Bool {\n";
print OUT "        switch self {\n";
foreach my $name (keys %$codecs) {
  if (exists $codecs->{$name}{real_name}) {
    print OUT "        case .$codecs->{$name}{name}:\n";
  } else {
    print OUT "        case .$name:\n";
  }
  if($codecs->{$name}{intra_frame_only} == 1) {
    print OUT "            true\n";
  } else {
    print OUT "            false\n";
  }
}
print OUT "        }\n";
print OUT "    }\n\n";


print OUT "    public var isLossy: Bool {\n";
print OUT "        switch self {\n";
foreach my $name (keys %$codecs) {
  if (exists $codecs->{$name}{real_name}) {
    print OUT "        case .$codecs->{$name}{name}:\n";
  } else {
    print OUT "        case .$name:\n";
  }
  if($codecs->{$name}{lossy} == 1) {
    print OUT "            true\n";
  } else {
    print OUT "            false\n";
  }
}
print OUT "        }\n";
print OUT "    }\n\n";


print OUT "    public var isLossless: Bool {\n";
print OUT "        switch self {\n";
foreach my $name (keys %$codecs) {
  if (exists $codecs->{$name}{real_name}) {
    print OUT "        case .$codecs->{$name}{name}:\n";
  } else {
    print OUT "        case .$name:\n";
  }
  if($codecs->{$name}{lossless} == 1) {
    print OUT "            true\n";
  } else {
    print OUT "            false\n";
  }
}
print OUT "        }\n";
print OUT "    }\n\n";

print OUT "    public var description: String {\n";
print OUT "        switch self {\n";
foreach my $name (keys %$codecs) {
  if (exists $codecs->{$name}{real_name}) {
    print OUT "        case .$codecs->{$name}{name}:\n";
  } else {
    print OUT "        case .$name:\n";
  }
  print OUT "            \"$codecs->{$name}{description}\"\n";
}
print OUT "        }\n";
print OUT "    }\n\n";


print OUT "    public var type: CodecType {\n";
print OUT "        switch self {\n";
foreach my $name (keys %$codecs) {
  if (exists $codecs->{$name}{real_name}) {
    print OUT "        case .$codecs->{$name}{name}:\n";
  } else {
    print OUT "        case .$name:\n";
  }
  my $type = $codecs->{$name}{codec_type};
  if($type eq 'V') {
      print OUT "            .video\n";
  } elsif($type eq 'A') {
      print OUT "            .audio\n";
  } elsif($type eq 'S') {
      print OUT "            .subtitle\n";
  } elsif($type eq 'D') {
      print OUT "            .data\n";
  } elsif($type eq 'T') {
      print OUT "            .attachment\n";
  } else {
      print OUT "            .none\n";
  }
}
print OUT "        }\n";
print OUT "    }\n\n";

my $extra_info = {};

foreach my $name (keys %$codecs) {
  my $real_name = $name;
  $real_name = $codecs->{$name}{name} if (exists $codecs->{$name}{real_name});
  open (FH, "../external_binaries/bin/ffmpeg -h encoder=$real_name 2>/dev/null |") || die "cannot read pix fmts: $!\n";
  my $supported_line = "[";
  while(<FH>) {
    if(/Supported pixel formats:\s+(.*)/) {

      my @supported_formats = split /\s+/, $1;
      foreach my $format (@supported_formats) {
	if ($format =~ /^\s*\d/) {
	  $supported_line .= "._$format, ";
	} else {
	  $supported_line .= ".$format, ";
	}
      }
    }
  }
  close FH;
  $supported_line .= "]";
  $extra_info->{$name}{supported_line} = $supported_line;
}

print OUT "    public var pixelFormats: [FFmpegPixelFormat] {\n";
print OUT "        switch self {\n";
foreach my $name (keys %$codecs) {
  my $real_name = $name;
  $real_name = $codecs->{$name}{name} if (exists $codecs->{$name}{real_name});
  print OUT "        case .$real_name:\n";
  print OUT "            $extra_info->{$name}{supported_line}\n";
}
print OUT "        }\n";
print OUT "    }\n\n";

print OUT "    public static var availableVideoCodecs: [FFmpegCodec] {\n";
print OUT "        self.allCases\n";
print OUT '          .filter { $0.canDecode }'."\n";
print OUT '          .filter { $0.canEncode }'."\n";
print OUT '          .filter { $0.pixelFormats.count > 0 }'."\n";
print OUT '          .filter { $0.type == .video }'."\n";
print OUT "    }\n";
print OUT "}\n\n";


print OUT "public enum CodecType: Codable {\n";
print OUT "    case video\n";
print OUT "    case audio\n";
print OUT "    case subtitle\n";
print OUT "    case data\n";
print OUT "    case attachment\n";
print OUT "    case none\n";
print OUT "}\n";
