import Foundation

// do not edit this file by hand, it was generated by ./outlier_analysis.pl
// from 6882 airplane outlier group records
// and 4446 airplane outlier group records

let airplane_keys_over_lines_avg = 0.0454918527758866
let airplane_mid_value_avg = 0.0177131601425053

let non_airplane_keys_over_lines_avg = 0.127064383162395
let non_airplane_mid_value_avg = 0.529693555417884

let keys_over_lines_avg = 0.0862781179691407
let mid_index_avg = 0.273703357780195

