import Foundation

// XXX do not edit this file by hand, it's generated by ./outlier_analysis.pl

func should_paint_based_upon(lines: [Line]) -> Bool {
    if lines.count < 10 { return false }
    let first_count = lines[0].count
    let last_count = lines[lines.count-1].count
    let mid_count = (first_count - last_count) / 2
    var line_counts: Set<Int> = []
    var mid_value: Double?
    for (index, line) in lines.enumerated() {
        line_counts.insert(line.count)
        if mid_value == nil && lines[index].count <= mid_count {
            mid_value = Double(index) / Double(lines.count)
	}
    }
    let counts_over_lines = Double(line_counts.count) / Double(lines.count)
    if let mid_value = mid_value {
        if counts_over_lines < 0.0855806273192255,
	   mid_value < 0.267967978407067
	{
	    return true
        }
    }
    return false
}

