/*
   written by decision_tree_generator on 2025-01-26 16:38:10 +0000 in 0 seconds

   with training data consisting of:
     - 150 groups known to be positive
     - 2397 groups known to be negative

   from input data described by:
     - /qp/star_validated/01_26_2025-test-train

   This is tree number 3 of a forest

   This tree was NOT pruned with test data

*/

import Foundation
import StarCore

// DO NOT EDIT THIS FILE
// DO NOT EDIT THIS FILE
// DO NOT EDIT THIS FILE

public struct OutlierGroupDecisionTreeForest_f1656b41: DecisionTree {
    public init() { }
    public let sha256 = "f1656b41483cc1de508142618d4bcf22c7e0152f699182db3763c41c2daae2dd"
    public let name = "f1656b41"
    public let sha256Prefix = "f1656b41"
    public let maxDepth = -1
    public let type: ClassifierType = .tree(DecisionTreeParams(name: "f1656b41",
                                               inputSequences:         [
            "/qp/star_validated/01_26_2025-test-train"
        ],
                                               positiveTrainingSize: 150,
                                               negativeTrainingSize: 2397,
                                               decisionTypes: [
        .size,
        .width,
        .height,
        .centerX,
        .centerY,
        .minX,
        .minY,
        .maxX,
        .maxY,
        .hypotenuse,
        .aspectRatio,
        .fillAmount,
        .surfaceAreaRatio,
        .averagebrightness,
        .medianBrightness,
        .maxBrightness,
        .numberOfNearbyOutliersInSameFrame,
        .maxHoughTransformCount,
        .pixelBorderAmount,
        .averageLineVariance,
        .medianLineVariance,
        .lineLength,
        .nearbyDirectOverlapScore,
        .boundingBoxOverlapScore,
        .lineFillAmount,
        .borderBrightness,
        .bunchCount,
        .medianBunchSize,
        .maxBunchSize,
        .neighborLineThetaScore,
        .neighborLineRhoScore,
        .neighborLineSizeScore,
        .neighborLineBrightnessScore,
        .neighborLineDistanceScore
    ]
,
                                               decisionSplitTypes: [
        .median
    ]
,
                                               maxDepth: -1,
                                               pruned: false))
    
    public let generationSecondsSince1970 = 1737909490.301354

    // the list of decision types this tree did not use
    public let notUsedDecisionTypes: [OutlierGroupFeature] = [

    ]


    // a way to call into the decision tree without an OutlierGroup object
    // it's going to blow up unless supplied with the expected set of features
    // return value is between -1 and 1, 1 is paint
    public func classification(
       of features: [OutlierGroupFeature], // parallel
       and values: [Double]                 // arrays
      ) async -> Double
    {
        let featureData = OutlierGroupFeatureData(features: features, values: values)
        return await classification(of: featureData)
    }

    // the actual tree resides here
    // return value is between -1 and 1, 1 is paint
    public func classification(of group: ClassifiableOutlierGroup) async -> Double 
    {
        if await group.decisionTreeValueAsync(for: .maxBunchSize) < 90.0 {
            if await group.decisionTreeValueAsync(for: .medianBunchSize) < 33.0 {
                if await group.decisionTreeValueAsync(for: .maxBunchSize) < 36.0 {
                    if await group.decisionTreeValueAsync(for: .boundingBoxOverlapScore) < 0.04175388176401532 {
                        if await group.decisionTreeValueAsync(for: .borderBrightness) < 0.06130417805544709 {
                            return -1
                        } else {
                            if group.decisionTreeValue(for: .aspectRatio) < 0.7903780068728522 {
                                return await subtree_18263BBF_33C7_4BD8_BFC8_8BA1F82EF5F5(group)
                            } else {
                                return -1
                            }
                        }
                    } else {
                        if group.decisionTreeValue(for: .centerY) < 0.6274509803921569 {
                            if group.decisionTreeValue(for: .maxX) < 0.6354376257545271 {
                                return 1
                            } else {
                                return -1
                            }
                        } else {
                            return -1
                        }
                    }
                } else {
                    if group.decisionTreeValue(for: .centerY) < 0.5683446455505279 {
                        if group.decisionTreeValue(for: .maxBrightness) < 15709.0 {
                            if await group.decisionTreeValueAsync(for: .maxHoughTransformCount) < 12.804036267914594 {
                                return -1
                            } else {
                                return await subtree_C70ECA50_8A86_4243_A04A_AABB585F0FD7(group)
                            }
                        } else {
                            if group.decisionTreeValue(for: .surfaceAreaRatio) < 0.9658487963131406 {
                                return await subtree_7F88DB97_8170_4266_B8E3_4842438E8376(group)
                            } else {
                                return await subtree_0B71BF51_DE43_4686_871D_1991DAADF3AA(group)
                            }
                        }
                    } else {
                        if group.decisionTreeValue(for: .centerY) < 0.8065610859728507 {
                            if group.decisionTreeValue(for: .height) < 0.02441553544494721 {
                                return 1
                            } else {
                                return -1
                            }
                        } else {
                            return -1
                        }
                    }
                }
            } else {
                if group.decisionTreeValue(for: .height) < 0.003299396681749623 {
                    if group.decisionTreeValue(for: .centerY) < 0.8344645550527903 {
                        if group.decisionTreeValue(for: .centerY) < 0.6540346907993967 {
                            if group.decisionTreeValue(for: .fillAmount) < 0.44917184265010346 {
                                return -1
                            } else {
                                return 1
                            }
                        } else {
                            return 1
                        }
                    } else {
                        if group.decisionTreeValue(for: .maxY) < 0.8455882352941176 {
                            if group.decisionTreeValue(for: .height) < 0.0010369532428355958 {
                                return 1
                            } else {
                                return -1
                            }
                        } else {
                            return -1
                        }
                    }
                } else {
                    if group.decisionTreeValue(for: .averagebrightness) < 9791.5 {
                        if group.decisionTreeValue(for: .medianBrightness) < 5752.0 {
                            return -1
                        } else {
                            if group.decisionTreeValue(for: .centerX) < 0.6568158953722334 {
                                return await subtree_C831FEFB_A787_4D8B_9823_A0166E30DB63(group)
                            } else {
                                return -1
                            }
                        }
                    } else {
                        if await group.decisionTreeValueAsync(for: .numberOfNearbyOutliersInSameFrame) < 1.5 {
                            if group.decisionTreeValue(for: .maxX) < 0.5147761569416499 {
                                return await subtree_82230888_85F3_4607_ABFB_6CBF1C8EEF7C(group)
                            } else {
                                return 1
                            }
                        } else {
                            return 1
                        }
                    }
                }
            }
        } else {
            if group.decisionTreeValue(for: .maxY) < 0.6411199095022624 {
                if group.decisionTreeValue(for: .averagebrightness) < 7642.5 {
                    if group.decisionTreeValue(for: .averagebrightness) < 6118.5 {
                        if await group.decisionTreeValueAsync(for: .numberOfNearbyOutliersInSameFrame) < 1.5 {
                            if await group.decisionTreeValueAsync(for: .borderBrightness) < 0.04406121006076526 {
                                return await subtree_875FA1C2_191A_4691_A01B_D44E31871742(group)
                            } else {
                                return await subtree_49CF3EEF_6215_4DE3_A7E5_1F2856D9BEFC(group)
                            }
                        } else {
                            if group.decisionTreeValue(for: .aspectRatio) < 3.0641836173721826 {
                                return await subtree_C633540B_28F6_4004_BAE4_99D59FB9A602(group)
                            } else {
                                return 1
                            }
                        }
                    } else {
                        if await group.decisionTreeValueAsync(for: .borderBrightness) < 0.02888293469263277 {
                            if await group.decisionTreeValueAsync(for: .numberOfNearbyOutliersInSameFrame) < 0.5 {
                                return await subtree_6856E876_AC18_4B55_A6A9_18495A739C4B(group)
                            } else {
                                return 1
                            }
                        } else {
                            if group.decisionTreeValue(for: .centerY) < 0.5641025641025641 {
                                return await subtree_B74E2405_D646_43A5_9C6D_EEBD2F4DD1D6(group)
                            } else {
                                return await subtree_16C39AB5_BD66_4156_A742_9430265C77E3(group)
                            }
                        }
                    }
                } else {
                    return 1
                }
            } else {
                if group.decisionTreeValue(for: .centerY) < 0.8231523378582202 {
                    if group.decisionTreeValue(for: .aspectRatio) < 1.4597953216374269 {
                        if group.decisionTreeValue(for: .medianBrightness) < 6486.5 {
                            if group.decisionTreeValue(for: .maxBrightness) < 10580.5 {
                                return -1
                            } else {
                                return await subtree_12756AAD_938E_41EC_B2EB_9C5BE2765C8E(group)
                            }
                        } else {
                            if await group.decisionTreeValueAsync(for: .neighborLineSizeScore) < 1.648760980726367 {
                                return 1
                            } else {
                                return -1
                            }
                        }
                    } else {
                        return 1
                    }
                } else {
                    if group.decisionTreeValue(for: .maxY) < 0.8428544494720965 {
                        return 1
                    } else {
                        return -1
                    }
                }
            }
        }
    }


fileprivate func subtree_18263BBF_33C7_4BD8_BFC8_8BA1F82EF5F5(_ group: ClassifiableOutlierGroup) async -> Double {
        if group.decisionTreeValue(for: .aspectRatio) < 0.47238095238095235 {
            if await group.decisionTreeValueAsync(for: .numberOfNearbyOutliersInSameFrame) < 3.5 {
                return -1
            } else {
                return 1
            }
        } else {
            return -1
        }
}

fileprivate func subtree_C70ECA50_8A86_4243_A04A_AABB585F0FD7(_ group: ClassifiableOutlierGroup) async -> Double {
        if group.decisionTreeValue(for: .maxY) < 0.44042232277526394 {
            return -1
        } else {
            return 1
        }
}

fileprivate func subtree_7F88DB97_8170_4266_B8E3_4842438E8376(_ group: ClassifiableOutlierGroup) async -> Double {
        if group.decisionTreeValue(for: .maxBrightness) < 20860.5 {
            return -1
        } else {
            return 1
        }
}

fileprivate func subtree_0B71BF51_DE43_4686_871D_1991DAADF3AA(_ group: ClassifiableOutlierGroup) async -> Double {
        if await group.decisionTreeValueAsync(for: .averageLineVariance) < 15.647101331298833 {
            return 1
        } else {
            return -1
        }
}

fileprivate func subtree_C831FEFB_A787_4D8B_9823_A0166E30DB63(_ group: ClassifiableOutlierGroup) async -> Double {
        if group.decisionTreeValue(for: .surfaceAreaRatio) < 0.9589544619154584 {
            if await group.decisionTreeValueAsync(for: .maxHoughTransformCount) < 0.6663235546405901 {
                return 1
            } else {
                return -1
            }
        } else {
            return 1
        }
}

fileprivate func subtree_82230888_85F3_4607_ABFB_6CBF1C8EEF7C(_ group: ClassifiableOutlierGroup) async -> Double {
        if group.decisionTreeValue(for: .aspectRatio) < 0.5227678571428571 {
            return 1
        } else {
            return -1
        }
}

fileprivate func subtree_875FA1C2_191A_4691_A01B_D44E31871742(_ group: ClassifiableOutlierGroup) async -> Double {
        if group.decisionTreeValue(for: .medianBrightness) < 3814.5 {
            return 1
        } else {
            return -1
        }
}

fileprivate func subtree_49CF3EEF_6215_4DE3_A7E5_1F2856D9BEFC(_ group: ClassifiableOutlierGroup) async -> Double {
        if await group.decisionTreeValueAsync(for: .maxHoughTransformCount) < 8.762586206896552 {
            if await group.decisionTreeValueAsync(for: .neighborLineDistanceScore) < 0.026852414677566973 {
                return -1
            } else {
                return 1
            }
        } else {
            return 1
        }
}

fileprivate func subtree_C633540B_28F6_4004_BAE4_99D59FB9A602(_ group: ClassifiableOutlierGroup) async -> Double {
        if await group.decisionTreeValueAsync(for: .maxBunchSize) < 102.5 {
            return 1
        } else {
            return -1
        }
}

fileprivate func subtree_6856E876_AC18_4B55_A6A9_18495A739C4B(_ group: ClassifiableOutlierGroup) async -> Double {
        if group.decisionTreeValue(for: .maxY) < 0.5015082956259427 {
            if await group.decisionTreeValueAsync(for: .medianLineVariance) < 0.8694664872779531 {
                if group.decisionTreeValue(for: .averagebrightness) < 6613.0 {
                    return -1
                } else {
                    return 1
                }
            } else {
                return -1
            }
        } else {
            return 1
        }
}

fileprivate func subtree_B74E2405_D646_43A5_9C6D_EEBD2F4DD1D6(_ group: ClassifiableOutlierGroup) async -> Double {
        if group.decisionTreeValue(for: .medianBrightness) < 5921.0 {
            return 1
        } else {
            return -1
        }
}

fileprivate func subtree_16C39AB5_BD66_4156_A742_9430265C77E3(_ group: ClassifiableOutlierGroup) async -> Double {
        if group.decisionTreeValue(for: .medianBrightness) < 6003.0 {
            return -1
        } else {
            return 1
        }
}

fileprivate func subtree_12756AAD_938E_41EC_B2EB_9C5BE2765C8E(_ group: ClassifiableOutlierGroup) async -> Double {
        if group.decisionTreeValue(for: .surfaceAreaRatio) < 0.8742844161744662 {
            return 1
        } else {
            return -1
        }
}
}