/*
   written by decision_tree_generator on 2025-01-26 16:38:10 +0000 in 0 seconds

   with training data consisting of:
     - 150 groups known to be positive
     - 2398 groups known to be negative

   from input data described by:
     - /qp/star_validated/01_26_2025-test-train

   This is tree number 6 of a forest

   This tree was NOT pruned with test data

*/

import Foundation
import StarCore

// DO NOT EDIT THIS FILE
// DO NOT EDIT THIS FILE
// DO NOT EDIT THIS FILE

public struct OutlierGroupDecisionTreeForest_871e365b: DecisionTree {
    public init() { }
    public let sha256 = "871e365b86fc4dd8d27fcebcffe439eb20b524f31c728546a69dc996afd95a1c"
    public let name = "871e365b"
    public let sha256Prefix = "871e365b"
    public let maxDepth = -1
    public let type: ClassifierType = .tree(DecisionTreeParams(name: "871e365b",
                                               inputSequences:         [
            "/qp/star_validated/01_26_2025-test-train"
        ],
                                               positiveTrainingSize: 150,
                                               negativeTrainingSize: 2398,
                                               decisionTypes: [
        .size,
        .width,
        .height,
        .centerX,
        .centerY,
        .minX,
        .minY,
        .maxX,
        .maxY,
        .hypotenuse,
        .aspectRatio,
        .fillAmount,
        .surfaceAreaRatio,
        .averagebrightness,
        .medianBrightness,
        .maxBrightness,
        .numberOfNearbyOutliersInSameFrame,
        .maxHoughTransformCount,
        .pixelBorderAmount,
        .averageLineVariance,
        .medianLineVariance,
        .lineLength,
        .nearbyDirectOverlapScore,
        .boundingBoxOverlapScore,
        .lineFillAmount,
        .borderBrightness,
        .bunchCount,
        .medianBunchSize,
        .maxBunchSize,
        .neighborLineThetaScore,
        .neighborLineRhoScore,
        .neighborLineSizeScore,
        .neighborLineBrightnessScore,
        .neighborLineDistanceScore
    ]
,
                                               decisionSplitTypes: [
        .median
    ]
,
                                               maxDepth: -1,
                                               pruned: false))
    
    public let generationSecondsSince1970 = 1737909490.301923

    // the list of decision types this tree did not use
    public let notUsedDecisionTypes: [OutlierGroupFeature] = [

    ]


    // a way to call into the decision tree without an OutlierGroup object
    // it's going to blow up unless supplied with the expected set of features
    // return value is between -1 and 1, 1 is paint
    public func classification(
       of features: [OutlierGroupFeature], // parallel
       and values: [Double]                 // arrays
      ) async -> Double
    {
        let featureData = OutlierGroupFeatureData(features: features, values: values)
        return await classification(of: featureData)
    }

    // the actual tree resides here
    // return value is between -1 and 1, 1 is paint
    public func classification(of group: ClassifiableOutlierGroup) async -> Double 
    {
        if await group.decisionTreeValueAsync(for: .maxBunchSize) < 90.0 {
            if await group.decisionTreeValueAsync(for: .medianBunchSize) < 32.5 {
                if await group.decisionTreeValueAsync(for: .maxBunchSize) < 35.5 {
                    if await group.decisionTreeValueAsync(for: .borderBrightness) < 0.06101792943898207 {
                        return -1
                    } else {
                        if group.decisionTreeValue(for: .fillAmount) < 0.38617149758454106 {
                            return -1
                        } else {
                            if group.decisionTreeValue(for: .width) < 0.00044014084507042255 {
                                return await subtree_DA8D2E76_B2E1_4CFC_87FE_47A7A3602896(group)
                            } else {
                                return await subtree_8F933C54_DC08_4E14_8D70_71B5ACEA988E(group)
                            }
                        }
                    }
                } else {
                    if group.decisionTreeValue(for: .minY) < 0.5447775263951734 {
                        if group.decisionTreeValue(for: .maxBrightness) < 16113.0 {
                            if group.decisionTreeValue(for: .minY) < 0.5213989441930619 {
                                return -1
                            } else {
                                return 1
                            }
                        } else {
                            if await group.decisionTreeValueAsync(for: .lineFillAmount) < 9.306627143964755 {
                                return await subtree_1B371B1A_BD20_4111_8FBE_4B769ACCE8BF(group)
                            } else {
                                return 1
                            }
                        }
                    } else {
                        if group.decisionTreeValue(for: .centerY) < 0.7957202111613877 {
                            if group.decisionTreeValue(for: .averagebrightness) < 9074.5 {
                                return -1
                            } else {
                                return 1
                            }
                        } else {
                            return -1
                        }
                    }
                }
            } else {
                if group.decisionTreeValue(for: .maxY) < 0.6741138763197587 {
                    if group.decisionTreeValue(for: .maxBrightness) < 15198.0 {
                        if group.decisionTreeValue(for: .medianBrightness) < 5445.0 {
                            return -1
                        } else {
                            if group.decisionTreeValue(for: .centerX) < 0.6335513078470825 {
                                return await subtree_7C2B8E26_5623_40F9_93A4_D85F816F33C6(group)
                            } else {
                                return -1
                            }
                        }
                    } else {
                        if await group.decisionTreeValueAsync(for: .numberOfNearbyOutliersInSameFrame) < 1.0 {
                            if await group.decisionTreeValueAsync(for: .bunchCount) < 4.5 {
                                return -1
                            } else {
                                return 1
                            }
                        } else {
                            if await group.decisionTreeValueAsync(for: .numberOfNearbyOutliersInSameFrame) < 4.0 {
                                return 1
                            } else {
                                return -1
                            }
                        }
                    }
                } else {
                    if group.decisionTreeValue(for: .centerY) < 0.8346530920060331 {
                        if group.decisionTreeValue(for: .averagebrightness) < 6023.0 {
                            return -1
                        } else {
                            return 1
                        }
                    } else {
                        if group.decisionTreeValue(for: .maxY) < 0.8455882352941176 {
                            if group.decisionTreeValue(for: .height) < 0.0009426847662141781 {
                                return 1
                            } else {
                                return -1
                            }
                        } else {
                            return -1
                        }
                    }
                }
            }
        } else {
            if group.decisionTreeValue(for: .height) < 0.009709653092006033 {
                if group.decisionTreeValue(for: .centerY) < 0.8083521870286576 {
                    if group.decisionTreeValue(for: .averagebrightness) < 7864.0 {
                        if await group.decisionTreeValueAsync(for: .maxBunchSize) < 147.0 {
                            if group.decisionTreeValue(for: .surfaceAreaRatio) < 0.920981308411215 {
                                return await subtree_96D9D484_AB8A_470E_8C38_77F9BBE8029B(group)
                            } else {
                                return await subtree_FEA13088_F4B0_4D3F_8B13_878B8B167BF6(group)
                            }
                        } else {
                            if await group.decisionTreeValueAsync(for: .borderBrightness) < 0.013128064910908002 {
                                return -1
                            } else {
                                return 1
                            }
                        }
                    } else {
                        return 1
                    }
                } else {
                    if group.decisionTreeValue(for: .maxY) < 0.8428544494720965 {
                        return 1
                    } else {
                        return -1
                    }
                }
            } else {
                if group.decisionTreeValue(for: .averagebrightness) < 7804.5 {
                    if group.decisionTreeValue(for: .averagebrightness) < 6130.0 {
                        if await group.decisionTreeValueAsync(for: .medianLineVariance) < 3.5005127120397193 {
                            if await group.decisionTreeValueAsync(for: .borderBrightness) < 0.0761310224797557 {
                                return await subtree_E745C5DE_D2C0_4296_BB21_E274847A56B7(group)
                            } else {
                                return await subtree_2ED1EA67_5847_4933_90E5_48F2C53D189C(group)
                            }
                        } else {
                            if await group.decisionTreeValueAsync(for: .medianBunchSize) < 7.5 {
                                return -1
                            } else {
                                return 1
                            }
                        }
                    } else {
                        if await group.decisionTreeValueAsync(for: .medianBunchSize) < 91.5 {
                            if await group.decisionTreeValueAsync(for: .borderBrightness) < 0.0297689866967941 {
                                return await subtree_3F36A027_77A2_4FE7_8CB9_8E27203030BF(group)
                            } else {
                                return await subtree_49476B2B_6530_4CCE_9298_AF6132A8F98F(group)
                            }
                        } else {
                            if await group.decisionTreeValueAsync(for: .bunchCount) < 3.5 {
                                return 1
                            } else {
                                return -1
                            }
                        }
                    }
                } else {
                    return 1
                }
            }
        }
    }


fileprivate func subtree_DA8D2E76_B2E1_4CFC_87FE_47A7A3602896(_ group: ClassifiableOutlierGroup) async -> Double {
        if group.decisionTreeValue(for: .aspectRatio) < 1.05 {
            if group.decisionTreeValue(for: .height) < 0.0010369532428355958 {
                return -1
            } else {
                if await group.decisionTreeValueAsync(for: .numberOfNearbyOutliersInSameFrame) < 3.5 {
                    return -1
                } else {
                    return 1
                }
            }
        } else {
            if group.decisionTreeValue(for: .centerX) < 0.6557469818913481 {
                return 1
            } else {
                return -1
            }
        }
}

fileprivate func subtree_8F933C54_DC08_4E14_8D70_71B5ACEA988E(_ group: ClassifiableOutlierGroup) async -> Double {
        if await group.decisionTreeValueAsync(for: .boundingBoxOverlapScore) < 0.041666666666666664 {
            return -1
        } else {
            if group.decisionTreeValue(for: .surfaceAreaRatio) < 0.8958333333333333 {
                return 1
            } else {
                return -1
            }
        }
}

fileprivate func subtree_1B371B1A_BD20_4111_8FBE_4B769ACCE8BF(_ group: ClassifiableOutlierGroup) async -> Double {
        if group.decisionTreeValue(for: .aspectRatio) < 2.920921985815603 {
            return -1
        } else {
            return 1
        }
}

fileprivate func subtree_7C2B8E26_5623_40F9_93A4_D85F816F33C6(_ group: ClassifiableOutlierGroup) async -> Double {
        if group.decisionTreeValue(for: .surfaceAreaRatio) < 0.9589544619154584 {
            if group.decisionTreeValue(for: .surfaceAreaRatio) < 0.9302238805970149 {
                return 1
            } else {
                return -1
            }
        } else {
            return 1
        }
}

fileprivate func subtree_96D9D484_AB8A_470E_8C38_77F9BBE8029B(_ group: ClassifiableOutlierGroup) async -> Double {
        if group.decisionTreeValue(for: .medianBrightness) < 4899.5 {
            return -1
        } else {
            return 1
        }
}

fileprivate func subtree_FEA13088_F4B0_4D3F_8B13_878B8B167BF6(_ group: ClassifiableOutlierGroup) async -> Double {
        if group.decisionTreeValue(for: .averagebrightness) < 4004.5 {
            return 1
        } else {
            return -1
        }
}

fileprivate func subtree_E745C5DE_D2C0_4296_BB21_E274847A56B7(_ group: ClassifiableOutlierGroup) async -> Double {
        if await group.decisionTreeValueAsync(for: .medianLineVariance) < 1.6789341262053923 {
            return -1
        } else {
            if await group.decisionTreeValueAsync(for: .neighborLineRhoScore) < 0.4264326633301664 {
                return -1
            } else {
                return 1
            }
        }
}

fileprivate func subtree_2ED1EA67_5847_4933_90E5_48F2C53D189C(_ group: ClassifiableOutlierGroup) async -> Double {
        if group.decisionTreeValue(for: .centerX) < 0.44422786720321933 {
            return -1
        } else {
            return 1
        }
}

fileprivate func subtree_3F36A027_77A2_4FE7_8CB9_8E27203030BF(_ group: ClassifiableOutlierGroup) async -> Double {
        if await group.decisionTreeValueAsync(for: .borderBrightness) < 0.024400863211297467 {
            return 1
        } else {
            return -1
        }
}

fileprivate func subtree_49476B2B_6530_4CCE_9298_AF6132A8F98F(_ group: ClassifiableOutlierGroup) async -> Double {
        if await group.decisionTreeValueAsync(for: .medianBunchSize) < 18.0 {
            return -1
        } else {
            return 1
        }
}
}