/*
   written by decision_tree_generator on 2025-07-06 22:58:36 +0000.

   The classifications of 8 trees are combined here with weights from test data.
   
   Trees were computed to the maximum depth possible

   tree(StarCore.DecisionTreeParams(name: "481f67ea", inputSequences: ["/qp/star_validated/7_6_2025-small-test-train"], positiveTrainingSize: 10281, negativeTrainingSize: 302790, decisionTypes: [StarCore.OutlierGroupFeature.size, StarCore.OutlierGroupFeature.width, StarCore.OutlierGroupFeature.height, StarCore.OutlierGroupFeature.centerX, StarCore.OutlierGroupFeature.centerY, StarCore.OutlierGroupFeature.minX, StarCore.OutlierGroupFeature.minY, StarCore.OutlierGroupFeature.maxX, StarCore.OutlierGroupFeature.maxY, StarCore.OutlierGroupFeature.hypotenuse, StarCore.OutlierGroupFeature.aspectRatio, StarCore.OutlierGroupFeature.fillAmount, StarCore.OutlierGroupFeature.surfaceAreaRatio, StarCore.OutlierGroupFeature.averagebrightness, StarCore.OutlierGroupFeature.medianBrightness, StarCore.OutlierGroupFeature.maxBrightness, StarCore.OutlierGroupFeature.numberOfNearbyOutliersInSameFrame, StarCore.OutlierGroupFeature.maxHoughTransformCount, StarCore.OutlierGroupFeature.pixelBorderAmount, StarCore.OutlierGroupFeature.averageLineVariance, StarCore.OutlierGroupFeature.medianLineVariance, StarCore.OutlierGroupFeature.lineLength, StarCore.OutlierGroupFeature.nearbyDirectOverlapScore, StarCore.OutlierGroupFeature.boundingBoxOverlapScore, StarCore.OutlierGroupFeature.lineIntensityScore, StarCore.OutlierGroupFeature.linePixelScore, StarCore.OutlierGroupFeature.borderBrightness, StarCore.OutlierGroupFeature.bunchCount, StarCore.OutlierGroupFeature.medianBunchSize, StarCore.OutlierGroupFeature.maxBunchSize, StarCore.OutlierGroupFeature.neighborLineThetaScore, StarCore.OutlierGroupFeature.neighborLineRhoScore, StarCore.OutlierGroupFeature.neighborLineSizeScore, StarCore.OutlierGroupFeature.neighborLineBrightnessScore, StarCore.OutlierGroupFeature.neighborLineDistanceScore], decisionSplitTypes: [StarCore.DecisionSplitType.median], maxDepth: Optional(-1), pruned: false))

   tree(StarCore.DecisionTreeParams(name: "303e2895", inputSequences: ["/qp/star_validated/7_6_2025-small-test-train"], positiveTrainingSize: 10281, negativeTrainingSize: 302790, decisionTypes: [StarCore.OutlierGroupFeature.size, StarCore.OutlierGroupFeature.width, StarCore.OutlierGroupFeature.height, StarCore.OutlierGroupFeature.centerX, StarCore.OutlierGroupFeature.centerY, StarCore.OutlierGroupFeature.minX, StarCore.OutlierGroupFeature.minY, StarCore.OutlierGroupFeature.maxX, StarCore.OutlierGroupFeature.maxY, StarCore.OutlierGroupFeature.hypotenuse, StarCore.OutlierGroupFeature.aspectRatio, StarCore.OutlierGroupFeature.fillAmount, StarCore.OutlierGroupFeature.surfaceAreaRatio, StarCore.OutlierGroupFeature.averagebrightness, StarCore.OutlierGroupFeature.medianBrightness, StarCore.OutlierGroupFeature.maxBrightness, StarCore.OutlierGroupFeature.numberOfNearbyOutliersInSameFrame, StarCore.OutlierGroupFeature.maxHoughTransformCount, StarCore.OutlierGroupFeature.pixelBorderAmount, StarCore.OutlierGroupFeature.averageLineVariance, StarCore.OutlierGroupFeature.medianLineVariance, StarCore.OutlierGroupFeature.lineLength, StarCore.OutlierGroupFeature.nearbyDirectOverlapScore, StarCore.OutlierGroupFeature.boundingBoxOverlapScore, StarCore.OutlierGroupFeature.lineIntensityScore, StarCore.OutlierGroupFeature.linePixelScore, StarCore.OutlierGroupFeature.borderBrightness, StarCore.OutlierGroupFeature.bunchCount, StarCore.OutlierGroupFeature.medianBunchSize, StarCore.OutlierGroupFeature.maxBunchSize, StarCore.OutlierGroupFeature.neighborLineThetaScore, StarCore.OutlierGroupFeature.neighborLineRhoScore, StarCore.OutlierGroupFeature.neighborLineSizeScore, StarCore.OutlierGroupFeature.neighborLineBrightnessScore, StarCore.OutlierGroupFeature.neighborLineDistanceScore], decisionSplitTypes: [StarCore.DecisionSplitType.median], maxDepth: Optional(-1), pruned: false))

   tree(StarCore.DecisionTreeParams(name: "da815feb", inputSequences: ["/qp/star_validated/7_6_2025-small-test-train"], positiveTrainingSize: 10281, negativeTrainingSize: 302790, decisionTypes: [StarCore.OutlierGroupFeature.size, StarCore.OutlierGroupFeature.width, StarCore.OutlierGroupFeature.height, StarCore.OutlierGroupFeature.centerX, StarCore.OutlierGroupFeature.centerY, StarCore.OutlierGroupFeature.minX, StarCore.OutlierGroupFeature.minY, StarCore.OutlierGroupFeature.maxX, StarCore.OutlierGroupFeature.maxY, StarCore.OutlierGroupFeature.hypotenuse, StarCore.OutlierGroupFeature.aspectRatio, StarCore.OutlierGroupFeature.fillAmount, StarCore.OutlierGroupFeature.surfaceAreaRatio, StarCore.OutlierGroupFeature.averagebrightness, StarCore.OutlierGroupFeature.medianBrightness, StarCore.OutlierGroupFeature.maxBrightness, StarCore.OutlierGroupFeature.numberOfNearbyOutliersInSameFrame, StarCore.OutlierGroupFeature.maxHoughTransformCount, StarCore.OutlierGroupFeature.pixelBorderAmount, StarCore.OutlierGroupFeature.averageLineVariance, StarCore.OutlierGroupFeature.medianLineVariance, StarCore.OutlierGroupFeature.lineLength, StarCore.OutlierGroupFeature.nearbyDirectOverlapScore, StarCore.OutlierGroupFeature.boundingBoxOverlapScore, StarCore.OutlierGroupFeature.lineIntensityScore, StarCore.OutlierGroupFeature.linePixelScore, StarCore.OutlierGroupFeature.borderBrightness, StarCore.OutlierGroupFeature.bunchCount, StarCore.OutlierGroupFeature.medianBunchSize, StarCore.OutlierGroupFeature.maxBunchSize, StarCore.OutlierGroupFeature.neighborLineThetaScore, StarCore.OutlierGroupFeature.neighborLineRhoScore, StarCore.OutlierGroupFeature.neighborLineSizeScore, StarCore.OutlierGroupFeature.neighborLineBrightnessScore, StarCore.OutlierGroupFeature.neighborLineDistanceScore], decisionSplitTypes: [StarCore.DecisionSplitType.median], maxDepth: Optional(-1), pruned: false))

   tree(StarCore.DecisionTreeParams(name: "bcb39431", inputSequences: ["/qp/star_validated/7_6_2025-small-test-train"], positiveTrainingSize: 10281, negativeTrainingSize: 302790, decisionTypes: [StarCore.OutlierGroupFeature.size, StarCore.OutlierGroupFeature.width, StarCore.OutlierGroupFeature.height, StarCore.OutlierGroupFeature.centerX, StarCore.OutlierGroupFeature.centerY, StarCore.OutlierGroupFeature.minX, StarCore.OutlierGroupFeature.minY, StarCore.OutlierGroupFeature.maxX, StarCore.OutlierGroupFeature.maxY, StarCore.OutlierGroupFeature.hypotenuse, StarCore.OutlierGroupFeature.aspectRatio, StarCore.OutlierGroupFeature.fillAmount, StarCore.OutlierGroupFeature.surfaceAreaRatio, StarCore.OutlierGroupFeature.averagebrightness, StarCore.OutlierGroupFeature.medianBrightness, StarCore.OutlierGroupFeature.maxBrightness, StarCore.OutlierGroupFeature.numberOfNearbyOutliersInSameFrame, StarCore.OutlierGroupFeature.maxHoughTransformCount, StarCore.OutlierGroupFeature.pixelBorderAmount, StarCore.OutlierGroupFeature.averageLineVariance, StarCore.OutlierGroupFeature.medianLineVariance, StarCore.OutlierGroupFeature.lineLength, StarCore.OutlierGroupFeature.nearbyDirectOverlapScore, StarCore.OutlierGroupFeature.boundingBoxOverlapScore, StarCore.OutlierGroupFeature.lineIntensityScore, StarCore.OutlierGroupFeature.linePixelScore, StarCore.OutlierGroupFeature.borderBrightness, StarCore.OutlierGroupFeature.bunchCount, StarCore.OutlierGroupFeature.medianBunchSize, StarCore.OutlierGroupFeature.maxBunchSize, StarCore.OutlierGroupFeature.neighborLineThetaScore, StarCore.OutlierGroupFeature.neighborLineRhoScore, StarCore.OutlierGroupFeature.neighborLineSizeScore, StarCore.OutlierGroupFeature.neighborLineBrightnessScore, StarCore.OutlierGroupFeature.neighborLineDistanceScore], decisionSplitTypes: [StarCore.DecisionSplitType.median], maxDepth: Optional(-1), pruned: false))

   tree(StarCore.DecisionTreeParams(name: "c0132baa", inputSequences: ["/qp/star_validated/7_6_2025-small-test-train"], positiveTrainingSize: 10281, negativeTrainingSize: 302790, decisionTypes: [StarCore.OutlierGroupFeature.size, StarCore.OutlierGroupFeature.width, StarCore.OutlierGroupFeature.height, StarCore.OutlierGroupFeature.centerX, StarCore.OutlierGroupFeature.centerY, StarCore.OutlierGroupFeature.minX, StarCore.OutlierGroupFeature.minY, StarCore.OutlierGroupFeature.maxX, StarCore.OutlierGroupFeature.maxY, StarCore.OutlierGroupFeature.hypotenuse, StarCore.OutlierGroupFeature.aspectRatio, StarCore.OutlierGroupFeature.fillAmount, StarCore.OutlierGroupFeature.surfaceAreaRatio, StarCore.OutlierGroupFeature.averagebrightness, StarCore.OutlierGroupFeature.medianBrightness, StarCore.OutlierGroupFeature.maxBrightness, StarCore.OutlierGroupFeature.numberOfNearbyOutliersInSameFrame, StarCore.OutlierGroupFeature.maxHoughTransformCount, StarCore.OutlierGroupFeature.pixelBorderAmount, StarCore.OutlierGroupFeature.averageLineVariance, StarCore.OutlierGroupFeature.medianLineVariance, StarCore.OutlierGroupFeature.lineLength, StarCore.OutlierGroupFeature.nearbyDirectOverlapScore, StarCore.OutlierGroupFeature.boundingBoxOverlapScore, StarCore.OutlierGroupFeature.lineIntensityScore, StarCore.OutlierGroupFeature.linePixelScore, StarCore.OutlierGroupFeature.borderBrightness, StarCore.OutlierGroupFeature.bunchCount, StarCore.OutlierGroupFeature.medianBunchSize, StarCore.OutlierGroupFeature.maxBunchSize, StarCore.OutlierGroupFeature.neighborLineThetaScore, StarCore.OutlierGroupFeature.neighborLineRhoScore, StarCore.OutlierGroupFeature.neighborLineSizeScore, StarCore.OutlierGroupFeature.neighborLineBrightnessScore, StarCore.OutlierGroupFeature.neighborLineDistanceScore], decisionSplitTypes: [StarCore.DecisionSplitType.median], maxDepth: Optional(-1), pruned: false))

   tree(StarCore.DecisionTreeParams(name: "85ea0305", inputSequences: ["/qp/star_validated/7_6_2025-small-test-train"], positiveTrainingSize: 10281, negativeTrainingSize: 302790, decisionTypes: [StarCore.OutlierGroupFeature.size, StarCore.OutlierGroupFeature.width, StarCore.OutlierGroupFeature.height, StarCore.OutlierGroupFeature.centerX, StarCore.OutlierGroupFeature.centerY, StarCore.OutlierGroupFeature.minX, StarCore.OutlierGroupFeature.minY, StarCore.OutlierGroupFeature.maxX, StarCore.OutlierGroupFeature.maxY, StarCore.OutlierGroupFeature.hypotenuse, StarCore.OutlierGroupFeature.aspectRatio, StarCore.OutlierGroupFeature.fillAmount, StarCore.OutlierGroupFeature.surfaceAreaRatio, StarCore.OutlierGroupFeature.averagebrightness, StarCore.OutlierGroupFeature.medianBrightness, StarCore.OutlierGroupFeature.maxBrightness, StarCore.OutlierGroupFeature.numberOfNearbyOutliersInSameFrame, StarCore.OutlierGroupFeature.maxHoughTransformCount, StarCore.OutlierGroupFeature.pixelBorderAmount, StarCore.OutlierGroupFeature.averageLineVariance, StarCore.OutlierGroupFeature.medianLineVariance, StarCore.OutlierGroupFeature.lineLength, StarCore.OutlierGroupFeature.nearbyDirectOverlapScore, StarCore.OutlierGroupFeature.boundingBoxOverlapScore, StarCore.OutlierGroupFeature.lineIntensityScore, StarCore.OutlierGroupFeature.linePixelScore, StarCore.OutlierGroupFeature.borderBrightness, StarCore.OutlierGroupFeature.bunchCount, StarCore.OutlierGroupFeature.medianBunchSize, StarCore.OutlierGroupFeature.maxBunchSize, StarCore.OutlierGroupFeature.neighborLineThetaScore, StarCore.OutlierGroupFeature.neighborLineRhoScore, StarCore.OutlierGroupFeature.neighborLineSizeScore, StarCore.OutlierGroupFeature.neighborLineBrightnessScore, StarCore.OutlierGroupFeature.neighborLineDistanceScore], decisionSplitTypes: [StarCore.DecisionSplitType.median], maxDepth: Optional(-1), pruned: false))

   tree(StarCore.DecisionTreeParams(name: "59f3d48b", inputSequences: ["/qp/star_validated/7_6_2025-small-test-train"], positiveTrainingSize: 10282, negativeTrainingSize: 302791, decisionTypes: [StarCore.OutlierGroupFeature.size, StarCore.OutlierGroupFeature.width, StarCore.OutlierGroupFeature.height, StarCore.OutlierGroupFeature.centerX, StarCore.OutlierGroupFeature.centerY, StarCore.OutlierGroupFeature.minX, StarCore.OutlierGroupFeature.minY, StarCore.OutlierGroupFeature.maxX, StarCore.OutlierGroupFeature.maxY, StarCore.OutlierGroupFeature.hypotenuse, StarCore.OutlierGroupFeature.aspectRatio, StarCore.OutlierGroupFeature.fillAmount, StarCore.OutlierGroupFeature.surfaceAreaRatio, StarCore.OutlierGroupFeature.averagebrightness, StarCore.OutlierGroupFeature.medianBrightness, StarCore.OutlierGroupFeature.maxBrightness, StarCore.OutlierGroupFeature.numberOfNearbyOutliersInSameFrame, StarCore.OutlierGroupFeature.maxHoughTransformCount, StarCore.OutlierGroupFeature.pixelBorderAmount, StarCore.OutlierGroupFeature.averageLineVariance, StarCore.OutlierGroupFeature.medianLineVariance, StarCore.OutlierGroupFeature.lineLength, StarCore.OutlierGroupFeature.nearbyDirectOverlapScore, StarCore.OutlierGroupFeature.boundingBoxOverlapScore, StarCore.OutlierGroupFeature.lineIntensityScore, StarCore.OutlierGroupFeature.linePixelScore, StarCore.OutlierGroupFeature.borderBrightness, StarCore.OutlierGroupFeature.bunchCount, StarCore.OutlierGroupFeature.medianBunchSize, StarCore.OutlierGroupFeature.maxBunchSize, StarCore.OutlierGroupFeature.neighborLineThetaScore, StarCore.OutlierGroupFeature.neighborLineRhoScore, StarCore.OutlierGroupFeature.neighborLineSizeScore, StarCore.OutlierGroupFeature.neighborLineBrightnessScore, StarCore.OutlierGroupFeature.neighborLineDistanceScore], decisionSplitTypes: [StarCore.DecisionSplitType.median], maxDepth: Optional(-1), pruned: false))

   tree(StarCore.DecisionTreeParams(name: "82a59c39", inputSequences: ["/qp/star_validated/7_6_2025-small-test-train"], positiveTrainingSize: 10282, negativeTrainingSize: 302791, decisionTypes: [StarCore.OutlierGroupFeature.size, StarCore.OutlierGroupFeature.width, StarCore.OutlierGroupFeature.height, StarCore.OutlierGroupFeature.centerX, StarCore.OutlierGroupFeature.centerY, StarCore.OutlierGroupFeature.minX, StarCore.OutlierGroupFeature.minY, StarCore.OutlierGroupFeature.maxX, StarCore.OutlierGroupFeature.maxY, StarCore.OutlierGroupFeature.hypotenuse, StarCore.OutlierGroupFeature.aspectRatio, StarCore.OutlierGroupFeature.fillAmount, StarCore.OutlierGroupFeature.surfaceAreaRatio, StarCore.OutlierGroupFeature.averagebrightness, StarCore.OutlierGroupFeature.medianBrightness, StarCore.OutlierGroupFeature.maxBrightness, StarCore.OutlierGroupFeature.numberOfNearbyOutliersInSameFrame, StarCore.OutlierGroupFeature.maxHoughTransformCount, StarCore.OutlierGroupFeature.pixelBorderAmount, StarCore.OutlierGroupFeature.averageLineVariance, StarCore.OutlierGroupFeature.medianLineVariance, StarCore.OutlierGroupFeature.lineLength, StarCore.OutlierGroupFeature.nearbyDirectOverlapScore, StarCore.OutlierGroupFeature.boundingBoxOverlapScore, StarCore.OutlierGroupFeature.lineIntensityScore, StarCore.OutlierGroupFeature.linePixelScore, StarCore.OutlierGroupFeature.borderBrightness, StarCore.OutlierGroupFeature.bunchCount, StarCore.OutlierGroupFeature.medianBunchSize, StarCore.OutlierGroupFeature.maxBunchSize, StarCore.OutlierGroupFeature.neighborLineThetaScore, StarCore.OutlierGroupFeature.neighborLineRhoScore, StarCore.OutlierGroupFeature.neighborLineSizeScore, StarCore.OutlierGroupFeature.neighborLineBrightnessScore, StarCore.OutlierGroupFeature.neighborLineDistanceScore], decisionSplitTypes: [StarCore.DecisionSplitType.median], maxDepth: Optional(-1), pruned: false))


 */

import Foundation
import StarCore

// DO NOT EDIT THIS FILE
// DO NOT EDIT THIS FILE
// DO NOT EDIT THIS FILE

public struct OutlierGroupForestClassifier_2436760d: NamedOutlierGroupClassifier {

    public init() { }

    public let name = "2436760d"
    
    public let type: ClassifierType = .forest(DecisionForestParams(name: "2436760d",
                                                                   treeCount: 8,
                                                                   treeNames: [ "481f67ea", "303e2895", "da815feb", "bcb39431", "c0132baa", "85ea0305", "59f3d48b", "82a59c39"]))

    let tree_481f67ea = OutlierGroupDecisionTreeForest_481f67ea()
    let tree_303e2895 = OutlierGroupDecisionTreeForest_303e2895()
    let tree_da815feb = OutlierGroupDecisionTreeForest_da815feb()
    let tree_bcb39431 = OutlierGroupDecisionTreeForest_bcb39431()
    let tree_c0132baa = OutlierGroupDecisionTreeForest_c0132baa()
    let tree_85ea0305 = OutlierGroupDecisionTreeForest_85ea0305()
    let tree_59f3d48b = OutlierGroupDecisionTreeForest_59f3d48b()
    let tree_82a59c39 = OutlierGroupDecisionTreeForest_82a59c39()


    // returns -1 for negative, +1 for positive
    public func classification(of group: ClassifiableOutlierGroup) async -> Double {
        var total: Double = 0.0

        total += await self.tree_481f67ea.classification(of: group) * 0.9315826541905624
        total += await self.tree_303e2895.classification(of: group) * 0.9579686085119228
        total += await self.tree_da815feb.classification(of: group) * 0.9583962169232317
        total += await self.tree_bcb39431.classification(of: group) * 0.9409397323674414
        total += await self.tree_c0132baa.classification(of: group) * 0.9524348526008652
        total += await self.tree_85ea0305.classification(of: group) * 0.9443354462219539
        total += await self.tree_59f3d48b.classification(of: group) * 0.9378961666163598
        total += await self.tree_82a59c39.classification(of: group) * 0.9164151323070732

        return total / 8
    }

    // returns -1 for negative, +1 for positive
    public func classification (
       of features: [OutlierGroupFeature],   // parallel
       and values: [Double]                   // arrays
    ) async -> Double
    {
        var total: Double = 0.0
        
        let featureData = OutlierGroupFeatureData(features: features, values: values)
        
        total += await self.tree_481f67ea.classification(of: featureData) * 0.9315826541905624
        total += await self.tree_303e2895.classification(of: featureData) * 0.9579686085119228
        total += await self.tree_da815feb.classification(of: featureData) * 0.9583962169232317
        total += await self.tree_bcb39431.classification(of: featureData) * 0.9409397323674414
        total += await self.tree_c0132baa.classification(of: featureData) * 0.9524348526008652
        total += await self.tree_85ea0305.classification(of: featureData) * 0.9443354462219539
        total += await self.tree_59f3d48b.classification(of: featureData) * 0.9378961666163598
        total += await self.tree_82a59c39.classification(of: featureData) * 0.9164151323070732

        return total / 8
    }
}