/*
   written by decision_tree_generator on 2025-01-26 16:38:10 +0000 in 0 seconds

   with training data consisting of:
     - 149 groups known to be positive
     - 2397 groups known to be negative

   from input data described by:
     - /qp/star_validated/01_26_2025-test-train

   This is tree number 0 of a forest

   This tree was NOT pruned with test data

*/

import Foundation
import StarCore

// DO NOT EDIT THIS FILE
// DO NOT EDIT THIS FILE
// DO NOT EDIT THIS FILE

public struct OutlierGroupDecisionTreeForest_64ea38a8: DecisionTree {
    public init() { }
    public let sha256 = "64ea38a8db365e35a4c6c84a8ad8f54613cfecd0d4b8ff45dcc8152a6f43b08a"
    public let name = "64ea38a8"
    public let sha256Prefix = "64ea38a8"
    public let maxDepth = -1
    public let type: ClassifierType = .tree(DecisionTreeParams(name: "64ea38a8",
                                               inputSequences:         [
            "/qp/star_validated/01_26_2025-test-train"
        ],
                                               positiveTrainingSize: 149,
                                               negativeTrainingSize: 2397,
                                               decisionTypes: [
        .size,
        .width,
        .height,
        .centerX,
        .centerY,
        .minX,
        .minY,
        .maxX,
        .maxY,
        .hypotenuse,
        .aspectRatio,
        .fillAmount,
        .surfaceAreaRatio,
        .averagebrightness,
        .medianBrightness,
        .maxBrightness,
        .numberOfNearbyOutliersInSameFrame,
        .maxHoughTransformCount,
        .pixelBorderAmount,
        .averageLineVariance,
        .medianLineVariance,
        .lineLength,
        .nearbyDirectOverlapScore,
        .boundingBoxOverlapScore,
        .lineFillAmount,
        .borderBrightness,
        .bunchCount,
        .medianBunchSize,
        .maxBunchSize,
        .neighborLineThetaScore,
        .neighborLineRhoScore,
        .neighborLineSizeScore,
        .neighborLineBrightnessScore,
        .neighborLineDistanceScore
    ]
,
                                               decisionSplitTypes: [
        .median
    ]
,
                                               maxDepth: -1,
                                               pruned: false))
    
    public let generationSecondsSince1970 = 1737909490.300885

    // the list of decision types this tree did not use
    public let notUsedDecisionTypes: [OutlierGroupFeature] = [

    ]


    // a way to call into the decision tree without an OutlierGroup object
    // it's going to blow up unless supplied with the expected set of features
    // return value is between -1 and 1, 1 is paint
    public func classification(
       of features: [OutlierGroupFeature], // parallel
       and values: [Double]                 // arrays
      ) async -> Double
    {
        let featureData = OutlierGroupFeatureData(features: features, values: values)
        return await classification(of: featureData)
    }

    // the actual tree resides here
    // return value is between -1 and 1, 1 is paint
    public func classification(of group: ClassifiableOutlierGroup) async -> Double 
    {
        if await group.decisionTreeValueAsync(for: .maxBunchSize) < 94.5 {
            if await group.decisionTreeValueAsync(for: .medianBunchSize) < 32.5 {
                if await group.decisionTreeValueAsync(for: .maxBunchSize) < 35.5 {
                    if await group.decisionTreeValueAsync(for: .borderBrightness) < 0.060933448573898014 {
                        return -1
                    } else {
                        if group.decisionTreeValue(for: .fillAmount) < 0.38545150501672243 {
                            return -1
                        } else {
                            if group.decisionTreeValue(for: .width) < 0.00044014084507042255 {
                                return await subtree_A7073D5B_8FA5_4962_92E4_D38FE57A6809(group)
                            } else {
                                return await subtree_475D9DEC_9AAC_49D9_BD7E_920AFA52C69F(group)
                            }
                        }
                    }
                } else {
                    if group.decisionTreeValue(for: .size) < 7.160231373155979e-06 {
                        if group.decisionTreeValue(for: .centerY) < 0.6883484162895928 {
                            if group.decisionTreeValue(for: .averagebrightness) < 7519.0 {
                                return await subtree_A2079439_A567_489B_ABAC_7DB918A62BF6(group)
                            } else {
                                return 1
                            }
                        } else {
                            if group.decisionTreeValue(for: .maxY) < 0.758578431372549 {
                                return 1
                            } else {
                                return -1
                            }
                        }
                    } else {
                        if await group.decisionTreeValueAsync(for: .lineLength) < 332.5079966714301 {
                            return -1
                        } else {
                            if await group.decisionTreeValueAsync(for: .lineLength) < 726.320862568427 {
                                return 1
                            } else {
                                return -1
                            }
                        }
                    }
                }
            } else {
                if group.decisionTreeValue(for: .centerY) < 0.673736802413273 {
                    if group.decisionTreeValue(for: .averagebrightness) < 8728.5 {
                        if group.decisionTreeValue(for: .medianBrightness) < 5743.0 {
                            return -1
                        } else {
                            if group.decisionTreeValue(for: .centerX) < 0.6335513078470825 {
                                return await subtree_5C6CEF95_C8C6_4BBE_8A8F_553BA9415662(group)
                            } else {
                                return -1
                            }
                        }
                    } else {
                        if group.decisionTreeValue(for: .fillAmount) < 0.10116550116550116 {
                            if group.decisionTreeValue(for: .maxY) < 0.5049962292609351 {
                                return 1
                            } else {
                                return -1
                            }
                        } else {
                            return -1
                        }
                    }
                } else {
                    if group.decisionTreeValue(for: .centerY) < 0.8326734539969833 {
                        if await group.decisionTreeValueAsync(for: .borderBrightness) < 0.041941094619666046 {
                            return 1
                        } else {
                            return -1
                        }
                    } else {
                        if group.decisionTreeValue(for: .maxY) < 0.8465309200603318 {
                            if group.decisionTreeValue(for: .fillAmount) < 0.4439814814814815 {
                                return -1
                            } else {
                                return 1
                            }
                        } else {
                            return -1
                        }
                    }
                }
            }
        } else {
            if group.decisionTreeValue(for: .maxY) < 0.6341440422322775 {
                if group.decisionTreeValue(for: .averagebrightness) < 7666.0 {
                    if group.decisionTreeValue(for: .medianBrightness) < 5809.5 {
                        if group.decisionTreeValue(for: .height) < 0.012066365007541477 {
                            if await group.decisionTreeValueAsync(for: .numberOfNearbyOutliersInSameFrame) < 1.5 {
                                return await subtree_C83BB95A_B68A_43D4_ADC1_BF59EA7AAD05(group)
                            } else {
                                return 1
                            }
                        } else {
                            if group.decisionTreeValue(for: .fillAmount) < 0.028389413814019694 {
                                return await subtree_DBB0ACC2_04D0_4250_A0EE_AC82F55DE5DB(group)
                            } else {
                                return await subtree_29411B93_5C85_4911_AF46_39A226EB88BA(group)
                            }
                        }
                    } else {
                        if await group.decisionTreeValueAsync(for: .borderBrightness) < 0.027607280312352163 {
                            if group.decisionTreeValue(for: .centerX) < 0.3517354124748491 {
                                return await subtree_4BC50935_487C_4008_9EAE_DE4D5C54EB25(group)
                            } else {
                                return 1
                            }
                        } else {
                            if group.decisionTreeValue(for: .centerY) < 0.5731523378582202 {
                                return -1
                            } else {
                                return 1
                            }
                        }
                    }
                } else {
                    return 1
                }
            } else {
                if group.decisionTreeValue(for: .centerY) < 0.8250377073906485 {
                    if group.decisionTreeValue(for: .centerY) < 0.7229449472096531 {
                        if group.decisionTreeValue(for: .centerX) < 0.4284456740442656 {
                            if await group.decisionTreeValueAsync(for: .numberOfNearbyOutliersInSameFrame) < 1.5 {
                                return -1
                            } else {
                                return 1
                            }
                        } else {
                            if group.decisionTreeValue(for: .maxY) < 0.701734539969834 {
                                return 1
                            } else {
                                return -1
                            }
                        }
                    } else {
                        return 1
                    }
                } else {
                    if group.decisionTreeValue(for: .maxY) < 0.8428544494720965 {
                        return 1
                    } else {
                        return -1
                    }
                }
            }
        }
    }


fileprivate func subtree_A7073D5B_8FA5_4962_92E4_D38FE57A6809(_ group: ClassifiableOutlierGroup) async -> Double {
        if group.decisionTreeValue(for: .height) < 0.0009426847662141781 {
            if await group.decisionTreeValueAsync(for: .medianLineVariance) < 0.288434872255233 {
                return 1
            } else {
                return -1
            }
        } else {
            if group.decisionTreeValue(for: .size) < 2.3709375407801255e-07 {
                return 1
            } else {
                return -1
            }
        }
}

fileprivate func subtree_475D9DEC_9AAC_49D9_BD7E_920AFA52C69F(_ group: ClassifiableOutlierGroup) async -> Double {
        if await group.decisionTreeValueAsync(for: .boundingBoxOverlapScore) < 0.041666666666666664 {
            return -1
        } else {
            if group.decisionTreeValue(for: .surfaceAreaRatio) < 0.8958333333333333 {
                return 1
            } else {
                return -1
            }
        }
}

fileprivate func subtree_A2079439_A567_489B_ABAC_7DB918A62BF6(_ group: ClassifiableOutlierGroup) async -> Double {
        if group.decisionTreeValue(for: .width) < 0.02816901408450704 {
            return -1
        } else {
            return 1
        }
}

fileprivate func subtree_5C6CEF95_C8C6_4BBE_8A8F_553BA9415662(_ group: ClassifiableOutlierGroup) async -> Double {
        if group.decisionTreeValue(for: .surfaceAreaRatio) < 0.9589544619154584 {
            if group.decisionTreeValue(for: .size) < 4.243978197996425e-06 {
                if group.decisionTreeValue(for: .medianBrightness) < 7676.0 {
                    return -1
                } else {
                    return 1
                }
            } else {
                return 1
            }
        } else {
            return 1
        }
}

fileprivate func subtree_C83BB95A_B68A_43D4_ADC1_BF59EA7AAD05(_ group: ClassifiableOutlierGroup) async -> Double {
        if group.decisionTreeValue(for: .centerY) < 0.32032428355957765 {
            if group.decisionTreeValue(for: .minY) < 0.21304675716440424 {
                return -1
            } else {
                return 1
            }
        } else {
            return -1
        }
}

fileprivate func subtree_DBB0ACC2_04D0_4250_A0EE_AC82F55DE5DB(_ group: ClassifiableOutlierGroup) async -> Double {
        if await group.decisionTreeValueAsync(for: .lineFillAmount) < 9.0253198706105 {
            return 1
        } else {
            return -1
        }
}

fileprivate func subtree_29411B93_5C85_4911_AF46_39A226EB88BA(_ group: ClassifiableOutlierGroup) async -> Double {
        if group.decisionTreeValue(for: .hypotenuse) < 4.576475338944238e-06 {
            return -1
        } else {
            return 1
        }
}

fileprivate func subtree_4BC50935_487C_4008_9EAE_DE4D5C54EB25(_ group: ClassifiableOutlierGroup) async -> Double {
        if group.decisionTreeValue(for: .surfaceAreaRatio) < 0.9846869915258223 {
            return 1
        } else {
            if group.decisionTreeValue(for: .aspectRatio) < 7.765037593984962 {
                if group.decisionTreeValue(for: .pixelBorderAmount) < 0.9758402575043041 {
                    return -1
                } else {
                    return 1
                }
            } else {
                return 1
            }
        }
}
}