/*
   written by decision_tree_generator on 2025-01-26 16:38:10 +0000 in 0 seconds

   with training data consisting of:
     - 150 groups known to be positive
     - 2398 groups known to be negative

   from input data described by:
     - /qp/star_validated/01_26_2025-test-train

   This is tree number 4 of a forest

   This tree was NOT pruned with test data

*/

import Foundation
import StarCore

// DO NOT EDIT THIS FILE
// DO NOT EDIT THIS FILE
// DO NOT EDIT THIS FILE

public struct OutlierGroupDecisionTreeForest_59cdc951: DecisionTree {
    public init() { }
    public let sha256 = "59cdc9515348387036a08db064a7486b950c16bfacea089f064ee42480c2f4fc"
    public let name = "59cdc951"
    public let sha256Prefix = "59cdc951"
    public let maxDepth = -1
    public let type: ClassifierType = .tree(DecisionTreeParams(name: "59cdc951",
                                               inputSequences:         [
            "/qp/star_validated/01_26_2025-test-train"
        ],
                                               positiveTrainingSize: 150,
                                               negativeTrainingSize: 2398,
                                               decisionTypes: [
        .size,
        .width,
        .height,
        .centerX,
        .centerY,
        .minX,
        .minY,
        .maxX,
        .maxY,
        .hypotenuse,
        .aspectRatio,
        .fillAmount,
        .surfaceAreaRatio,
        .averagebrightness,
        .medianBrightness,
        .maxBrightness,
        .numberOfNearbyOutliersInSameFrame,
        .maxHoughTransformCount,
        .pixelBorderAmount,
        .averageLineVariance,
        .medianLineVariance,
        .lineLength,
        .nearbyDirectOverlapScore,
        .boundingBoxOverlapScore,
        .lineFillAmount,
        .borderBrightness,
        .bunchCount,
        .medianBunchSize,
        .maxBunchSize,
        .neighborLineThetaScore,
        .neighborLineRhoScore,
        .neighborLineSizeScore,
        .neighborLineBrightnessScore,
        .neighborLineDistanceScore
    ]
,
                                               decisionSplitTypes: [
        .median
    ]
,
                                               maxDepth: -1,
                                               pruned: false))
    
    public let generationSecondsSince1970 = 1737909490.301641

    // the list of decision types this tree did not use
    public let notUsedDecisionTypes: [OutlierGroupFeature] = [

    ]


    // a way to call into the decision tree without an OutlierGroup object
    // it's going to blow up unless supplied with the expected set of features
    // return value is between -1 and 1, 1 is paint
    public func classification(
       of features: [OutlierGroupFeature], // parallel
       and values: [Double]                 // arrays
      ) async -> Double
    {
        let featureData = OutlierGroupFeatureData(features: features, values: values)
        return await classification(of: featureData)
    }

    // the actual tree resides here
    // return value is between -1 and 1, 1 is paint
    public func classification(of group: ClassifiableOutlierGroup) async -> Double 
    {
        if await group.decisionTreeValueAsync(for: .maxBunchSize) < 90.0 {
            if await group.decisionTreeValueAsync(for: .medianBunchSize) < 32.5 {
                if await group.decisionTreeValueAsync(for: .maxBunchSize) < 35.5 {
                    if await group.decisionTreeValueAsync(for: .borderBrightness) < 0.060933448573898014 {
                        return -1
                    } else {
                        if group.decisionTreeValue(for: .fillAmount) < 0.38604900558949695 {
                            return -1
                        } else {
                            if group.decisionTreeValue(for: .width) < 0.00044014084507042255 {
                                return await subtree_B876FE27_6BC9_4513_9EAD_F7AEF0BEF66C(group)
                            } else {
                                return await subtree_6281965B_E171_4935_8590_1C8E40C8E532(group)
                            }
                        }
                    }
                } else {
                    if group.decisionTreeValue(for: .hypotenuse) < 5.592647166021537e-06 {
                        if group.decisionTreeValue(for: .centerY) < 0.5680618401206636 {
                            if group.decisionTreeValue(for: .averagebrightness) < 7614.0 {
                                return await subtree_C00F58C2_85F3_482A_9DD1_C90E8DC1469A(group)
                            } else {
                                return 1
                            }
                        } else {
                            if group.decisionTreeValue(for: .centerY) < 0.7959087481146305 {
                                return await subtree_AB3D67C9_475D_42C2_B924_ED6E3A4B55DA(group)
                            } else {
                                return -1
                            }
                        }
                    } else {
                        if await group.decisionTreeValueAsync(for: .lineLength) < 312.5371290272467 {
                            if group.decisionTreeValue(for: .hypotenuse) < 5.824012158443725e-06 {
                                return 1
                            } else {
                                return -1
                            }
                        } else {
                            if await group.decisionTreeValueAsync(for: .neighborLineDistanceScore) < 1.5124745511338749 {
                                return 1
                            } else {
                                return -1
                            }
                        }
                    }
                }
            } else {
                if group.decisionTreeValue(for: .height) < 0.0032051282051282055 {
                    if group.decisionTreeValue(for: .centerY) < 0.8344645550527903 {
                        if group.decisionTreeValue(for: .centerY) < 0.6540346907993967 {
                            if group.decisionTreeValue(for: .fillAmount) < 0.44917184265010346 {
                                return -1
                            } else {
                                return 1
                            }
                        } else {
                            return 1
                        }
                    } else {
                        if group.decisionTreeValue(for: .centerY) < 0.845211161387632 {
                            if group.decisionTreeValue(for: .height) < 0.0009426847662141781 {
                                return 1
                            } else {
                                return -1
                            }
                        } else {
                            return -1
                        }
                    }
                } else {
                    if group.decisionTreeValue(for: .averagebrightness) < 9898.5 {
                        if await group.decisionTreeValueAsync(for: .neighborLineRhoScore) < 0.3217476927019811 {
                            if group.decisionTreeValue(for: .surfaceAreaRatio) < 0.9593253968253967 {
                                return -1
                            } else {
                                return await subtree_C519ACD4_BA05_41D5_A0F7_A1A8734567ED(group)
                            }
                        } else {
                            if group.decisionTreeValue(for: .centerX) < 0.32344064386317906 {
                                return 1
                            } else {
                                return -1
                            }
                        }
                    } else {
                        if group.decisionTreeValue(for: .centerY) < 0.5593891402714932 {
                            if await group.decisionTreeValueAsync(for: .averageLineVariance) < 0.8558888328066606 {
                                return 1
                            } else {
                                return -1
                            }
                        } else {
                            if await group.decisionTreeValueAsync(for: .lineFillAmount) < 9.421441237787109 {
                                return 1
                            } else {
                                return -1
                            }
                        }
                    }
                }
            }
        } else {
            if group.decisionTreeValue(for: .maxY) < 0.6341440422322775 {
                if group.decisionTreeValue(for: .averagebrightness) < 7688.0 {
                    if group.decisionTreeValue(for: .averagebrightness) < 6064.5 {
                        if group.decisionTreeValue(for: .height) < 0.012160633484162896 {
                            if await group.decisionTreeValueAsync(for: .numberOfNearbyOutliersInSameFrame) < 2.0 {
                                return await subtree_610A7915_B5B0_4CD5_A83A_B637D841FF80(group)
                            } else {
                                return await subtree_8DC38EBD_04B8_471B_9339_D4956CE49AB1(group)
                            }
                        } else {
                            if group.decisionTreeValue(for: .maxBrightness) < 16519.0 {
                                return await subtree_49DA774F_BFC7_46EB_BDB9_B2C66806EBBB(group)
                            } else {
                                return await subtree_75DE3DC7_EA5F_4564_BC3E_F82B33047EC4(group)
                            }
                        }
                    } else {
                        if group.decisionTreeValue(for: .fillAmount) < 0.016860982916363048 {
                            if await group.decisionTreeValueAsync(for: .maxBunchSize) < 317.5 {
                                return await subtree_A0197D54_9681_410E_876F_2DE9FB8D9157(group)
                            } else {
                                return 1
                            }
                        } else {
                            if group.decisionTreeValue(for: .height) < 0.010558069381598794 {
                                return await subtree_21119EAE_A22E_4335_A9E4_DF04CE4138A7(group)
                            } else {
                                return 1
                            }
                        }
                    }
                } else {
                    return 1
                }
            } else {
                if group.decisionTreeValue(for: .centerY) < 0.8223039215686274 {
                    if group.decisionTreeValue(for: .aspectRatio) < 1.4538530465949822 {
                        if group.decisionTreeValue(for: .medianBrightness) < 6574.0 {
                            if group.decisionTreeValue(for: .maxBrightness) < 10580.5 {
                                return -1
                            } else {
                                return await subtree_25738E6E_1BC8_4122_B0A3_14E6811D7FCF(group)
                            }
                        } else {
                            if await group.decisionTreeValueAsync(for: .neighborLineSizeScore) < 1.648760980726367 {
                                return 1
                            } else {
                                return -1
                            }
                        }
                    } else {
                        return 1
                    }
                } else {
                    if group.decisionTreeValue(for: .maxY) < 0.8428544494720965 {
                        return 1
                    } else {
                        return -1
                    }
                }
            }
        }
    }


fileprivate func subtree_B876FE27_6BC9_4513_9EAD_F7AEF0BEF66C(_ group: ClassifiableOutlierGroup) async -> Double {
        if group.decisionTreeValue(for: .aspectRatio) < 1.0833333333333333 {
            if group.decisionTreeValue(for: .height) < 0.0009426847662141781 {
                return -1
            } else {
                if await group.decisionTreeValueAsync(for: .numberOfNearbyOutliersInSameFrame) < 3.5 {
                    return -1
                } else {
                    return 1
                }
            }
        } else {
            if group.decisionTreeValue(for: .centerX) < 0.6557469818913481 {
                return 1
            } else {
                return -1
            }
        }
}

fileprivate func subtree_6281965B_E171_4935_8590_1C8E40C8E532(_ group: ClassifiableOutlierGroup) async -> Double {
        if await group.decisionTreeValueAsync(for: .boundingBoxOverlapScore) < 0.041666666666666664 {
            return -1
        } else {
            if group.decisionTreeValue(for: .surfaceAreaRatio) < 0.8958333333333333 {
                return 1
            } else {
                return -1
            }
        }
}

fileprivate func subtree_C00F58C2_85F3_482A_9DD1_C90E8DC1469A(_ group: ClassifiableOutlierGroup) async -> Double {
        if group.decisionTreeValue(for: .maxBrightness) < 14641.0 {
            return -1
        } else {
            if await group.decisionTreeValueAsync(for: .numberOfNearbyOutliersInSameFrame) < 0.5 {
                return -1
            } else {
                return 1
            }
        }
}

fileprivate func subtree_AB3D67C9_475D_42C2_B924_ED6E3A4B55DA(_ group: ClassifiableOutlierGroup) async -> Double {
        if group.decisionTreeValue(for: .maxBrightness) < 17184.5 {
            return -1
        } else {
            return 1
        }
}

fileprivate func subtree_C519ACD4_BA05_41D5_A0F7_A1A8734567ED(_ group: ClassifiableOutlierGroup) async -> Double {
        if group.decisionTreeValue(for: .pixelBorderAmount) < 1.8193001640240567 {
            return -1
        } else {
            return 1
        }
}

fileprivate func subtree_610A7915_B5B0_4CD5_A83A_B637D841FF80(_ group: ClassifiableOutlierGroup) async -> Double {
        if group.decisionTreeValue(for: .centerY) < 0.32098416289592757 {
            if group.decisionTreeValue(for: .minY) < 0.21163273001508295 {
                return -1
            } else {
                return 1
            }
        } else {
            return -1
        }
}

fileprivate func subtree_8DC38EBD_04B8_471B_9339_D4956CE49AB1(_ group: ClassifiableOutlierGroup) async -> Double {
        if group.decisionTreeValue(for: .height) < 0.004336349924585219 {
            return 1
        } else {
            return -1
        }
}

fileprivate func subtree_49DA774F_BFC7_46EB_BDB9_B2C66806EBBB(_ group: ClassifiableOutlierGroup) async -> Double {
        if await group.decisionTreeValueAsync(for: .maxBunchSize) < 105.0 {
            return 1
        } else {
            return -1
        }
}

fileprivate func subtree_75DE3DC7_EA5F_4564_BC3E_F82B33047EC4(_ group: ClassifiableOutlierGroup) async -> Double {
        if group.decisionTreeValue(for: .size) < 2.2002300378439567e-05 {
            return -1
        } else {
            return 1
        }
}

fileprivate func subtree_A0197D54_9681_410E_876F_2DE9FB8D9157(_ group: ClassifiableOutlierGroup) async -> Double {
        if await group.decisionTreeValueAsync(for: .borderBrightness) < 0.028922155354850217 {
            if await group.decisionTreeValueAsync(for: .lineLength) < 470.26296074926995 {
                return 1
            } else {
                return -1
            }
        } else {
            return -1
        }
}

fileprivate func subtree_21119EAE_A22E_4335_A9E4_DF04CE4138A7(_ group: ClassifiableOutlierGroup) async -> Double {
        if await group.decisionTreeValueAsync(for: .maxBunchSize) < 154.0 {
            return -1
        } else {
            return 1
        }
}

fileprivate func subtree_25738E6E_1BC8_4122_B0A3_14E6811D7FCF(_ group: ClassifiableOutlierGroup) async -> Double {
        if group.decisionTreeValue(for: .surfaceAreaRatio) < 0.8742844161744662 {
            return 1
        } else {
            return -1
        }
}
}