/*
   written by decision_tree_generator on 2025-01-26 16:38:10 +0000 in 0 seconds

   with training data consisting of:
     - 150 groups known to be positive
     - 2398 groups known to be negative

   from input data described by:
     - /qp/star_validated/01_26_2025-test-train

   This is tree number 5 of a forest

   This tree was NOT pruned with test data

*/

import Foundation
import StarCore

// DO NOT EDIT THIS FILE
// DO NOT EDIT THIS FILE
// DO NOT EDIT THIS FILE

public struct OutlierGroupDecisionTreeForest_5bb97381: DecisionTree {
    public init() { }
    public let sha256 = "5bb973819b3bbefc45832c8fa66f5aad7a85d9ba1e4771297b513a267a32189d"
    public let name = "5bb97381"
    public let sha256Prefix = "5bb97381"
    public let maxDepth = -1
    public let type: ClassifierType = .tree(DecisionTreeParams(name: "5bb97381",
                                               inputSequences:         [
            "/qp/star_validated/01_26_2025-test-train"
        ],
                                               positiveTrainingSize: 150,
                                               negativeTrainingSize: 2398,
                                               decisionTypes: [
        .size,
        .width,
        .height,
        .centerX,
        .centerY,
        .minX,
        .minY,
        .maxX,
        .maxY,
        .hypotenuse,
        .aspectRatio,
        .fillAmount,
        .surfaceAreaRatio,
        .averagebrightness,
        .medianBrightness,
        .maxBrightness,
        .numberOfNearbyOutliersInSameFrame,
        .maxHoughTransformCount,
        .pixelBorderAmount,
        .averageLineVariance,
        .medianLineVariance,
        .lineLength,
        .nearbyDirectOverlapScore,
        .boundingBoxOverlapScore,
        .lineFillAmount,
        .borderBrightness,
        .bunchCount,
        .medianBunchSize,
        .maxBunchSize,
        .neighborLineThetaScore,
        .neighborLineRhoScore,
        .neighborLineSizeScore,
        .neighborLineBrightnessScore,
        .neighborLineDistanceScore
    ]
,
                                               decisionSplitTypes: [
        .median
    ]
,
                                               maxDepth: -1,
                                               pruned: false))
    
    public let generationSecondsSince1970 = 1737909490.3023539

    // the list of decision types this tree did not use
    public let notUsedDecisionTypes: [OutlierGroupFeature] = [

    ]


    // a way to call into the decision tree without an OutlierGroup object
    // it's going to blow up unless supplied with the expected set of features
    // return value is between -1 and 1, 1 is paint
    public func classification(
       of features: [OutlierGroupFeature], // parallel
       and values: [Double]                 // arrays
      ) async -> Double
    {
        let featureData = OutlierGroupFeatureData(features: features, values: values)
        return await classification(of: featureData)
    }

    // the actual tree resides here
    // return value is between -1 and 1, 1 is paint
    public func classification(of group: ClassifiableOutlierGroup) async -> Double 
    {
        if await group.decisionTreeValueAsync(for: .maxBunchSize) < 90.0 {
            if await group.decisionTreeValueAsync(for: .medianBunchSize) < 32.5 {
                if await group.decisionTreeValueAsync(for: .maxBunchSize) < 35.5 {
                    if await group.decisionTreeValueAsync(for: .borderBrightness) < 0.061007957559681705 {
                        return -1
                    } else {
                        if group.decisionTreeValue(for: .fillAmount) < 0.3860139293812763 {
                            return -1
                        } else {
                            if group.decisionTreeValue(for: .fillAmount) < 0.65625 {
                                return -1
                            } else {
                                return await subtree_4CFC8529_FDB4_4389_AF5C_A49826E8C455(group)
                            }
                        }
                    }
                } else {
                    if group.decisionTreeValue(for: .centerY) < 0.567684766214178 {
                        if group.decisionTreeValue(for: .maxBrightness) < 15709.0 {
                            return -1
                        } else {
                            if group.decisionTreeValue(for: .aspectRatio) < 2.375793650793651 {
                                return await subtree_244719DF_7D2E_4333_8EF1_3458E8047ED3(group)
                            } else {
                                return 1
                            }
                        }
                    } else {
                        if group.decisionTreeValue(for: .size) < 7.824093884574416e-06 {
                            if group.decisionTreeValue(for: .centerY) < 0.7957202111613877 {
                                return await subtree_1890A631_E9A8_476C_9128_53C191AEF39B(group)
                            } else {
                                return -1
                            }
                        } else {
                            if group.decisionTreeValue(for: .size) < 1.1985089268643534e-05 {
                                return -1
                            } else {
                                return 1
                            }
                        }
                    }
                }
            } else {
                if group.decisionTreeValue(for: .height) < 0.0034879336349924587 {
                    if group.decisionTreeValue(for: .centerY) < 0.8345588235294117 {
                        if await group.decisionTreeValueAsync(for: .neighborLineSizeScore) < 0.5772481040086674 {
                            if group.decisionTreeValue(for: .fillAmount) < 0.44917184265010346 {
                                return -1
                            } else {
                                return 1
                            }
                        } else {
                            return 1
                        }
                    } else {
                        if group.decisionTreeValue(for: .centerY) < 0.845211161387632 {
                            if group.decisionTreeValue(for: .height) < 0.0009426847662141781 {
                                return 1
                            } else {
                                return -1
                            }
                        } else {
                            return -1
                        }
                    }
                } else {
                    if group.decisionTreeValue(for: .averagebrightness) < 9814.5 {
                        if await group.decisionTreeValueAsync(for: .averageLineVariance) < 1.6791186105556668 {
                            if await group.decisionTreeValueAsync(for: .neighborLineRhoScore) < 0.47717991642806057 {
                                return await subtree_9671CD18_CFF2_40FE_95D6_0280324AB1FB(group)
                            } else {
                                return await subtree_A3BADBA6_93D4_4A02_ADAC_074EF51F449C(group)
                            }
                        } else {
                            if await group.decisionTreeValueAsync(for: .neighborLineThetaScore) < 0.4916666666666657 {
                                return -1
                            } else {
                                return 1
                            }
                        }
                    } else {
                        if group.decisionTreeValue(for: .maxY) < 0.7278469079939668 {
                            return 1
                        } else {
                            return -1
                        }
                    }
                }
            }
        } else {
            if group.decisionTreeValue(for: .height) < 0.01027526395173454 {
                if group.decisionTreeValue(for: .centerY) < 0.8083521870286576 {
                    if group.decisionTreeValue(for: .averagebrightness) < 7616.0 {
                        if await group.decisionTreeValueAsync(for: .maxBunchSize) < 159.5 {
                            if await group.decisionTreeValueAsync(for: .medianLineVariance) < 0.4253697537287723 {
                                return 1
                            } else {
                                return -1
                            }
                        } else {
                            if group.decisionTreeValue(for: .surfaceAreaRatio) < 0.9981949458483754 {
                                return await subtree_E6334F0A_ABA9_4FC1_8D5C_DEF1CB5E3934(group)
                            } else {
                                return 1
                            }
                        }
                    } else {
                        return 1
                    }
                } else {
                    if group.decisionTreeValue(for: .maxY) < 0.8431372549019608 {
                        return 1
                    } else {
                        return -1
                    }
                }
            } else {
                if group.decisionTreeValue(for: .medianBrightness) < 7444.5 {
                    if group.decisionTreeValue(for: .averagebrightness) < 6014.0 {
                        if await group.decisionTreeValueAsync(for: .medianLineVariance) < 3.444422971089764 {
                            if await group.decisionTreeValueAsync(for: .borderBrightness) < 0.07528605208449049 {
                                return await subtree_E77F509E_9C2E_41AD_BE97_107610CB4E39(group)
                            } else {
                                return await subtree_920E11FF_249C_4880_82B9_91A6E869F9F6(group)
                            }
                        } else {
                            if await group.decisionTreeValueAsync(for: .medianBunchSize) < 7.5 {
                                return -1
                            } else {
                                return 1
                            }
                        }
                    } else {
                        if await group.decisionTreeValueAsync(for: .borderBrightness) < 0.029302435703927314 {
                            if group.decisionTreeValue(for: .height) < 0.028563348416289592 {
                                return await subtree_6F9CB5B3_B047_456F_9549_88223C3FC492(group)
                            } else {
                                return 1
                            }
                        } else {
                            if group.decisionTreeValue(for: .fillAmount) < 0.021756205256567466 {
                                return -1
                            } else {
                                return 1
                            }
                        }
                    }
                } else {
                    if group.decisionTreeValue(for: .size) < 6.448950110921941e-06 {
                        if await group.decisionTreeValueAsync(for: .neighborLineSizeScore) < 1.456334516792979 {
                            return 1
                        } else {
                            return -1
                        }
                    } else {
                        return 1
                    }
                }
            }
        }
    }


fileprivate func subtree_4CFC8529_FDB4_4389_AF5C_A49826E8C455(_ group: ClassifiableOutlierGroup) async -> Double {
        if await group.decisionTreeValueAsync(for: .medianLineVariance) < 0.44240719714445154 {
            if group.decisionTreeValue(for: .centerX) < 0.6557469818913481 {
                return 1
            } else {
                if group.decisionTreeValue(for: .height) < 0.0009426847662141781 {
                    return -1
                } else {
                    return 1
                }
            }
        } else {
            return -1
        }
}

fileprivate func subtree_244719DF_7D2E_4333_8EF1_3458E8047ED3(_ group: ClassifiableOutlierGroup) async -> Double {
        if await group.decisionTreeValueAsync(for: .lineLength) < 313.1501699237132 {
            return -1
        } else {
            return 1
        }
}

fileprivate func subtree_1890A631_E9A8_476C_9128_53C191AEF39B(_ group: ClassifiableOutlierGroup) async -> Double {
        if await group.decisionTreeValueAsync(for: .medianBunchSize) < 21.5 {
            return -1
        } else {
            return 1
        }
}

fileprivate func subtree_9671CD18_CFF2_40FE_95D6_0280324AB1FB(_ group: ClassifiableOutlierGroup) async -> Double {
        if await group.decisionTreeValueAsync(for: .averageLineVariance) < 0.5575553832216265 {
            if await group.decisionTreeValueAsync(for: .maxHoughTransformCount) < 0.45410628019323673 {
                return 1
            } else {
                return -1
            }
        } else {
            return -1
        }
}

fileprivate func subtree_A3BADBA6_93D4_4A02_ADAC_074EF51F449C(_ group: ClassifiableOutlierGroup) async -> Double {
        if group.decisionTreeValue(for: .pixelBorderAmount) < 1.9654110400379055 {
            return -1
        } else {
            return 1
        }
}

fileprivate func subtree_E6334F0A_ABA9_4FC1_8D5C_DEF1CB5E3934(_ group: ClassifiableOutlierGroup) async -> Double {
        if await group.decisionTreeValueAsync(for: .maxHoughTransformCount) < 2.451489902556136 {
            if group.decisionTreeValue(for: .averagebrightness) < 6913.5 {
                return -1
            } else {
                return 1
            }
        } else {
            return 1
        }
}

fileprivate func subtree_E77F509E_9C2E_41AD_BE97_107610CB4E39(_ group: ClassifiableOutlierGroup) async -> Double {
        if await group.decisionTreeValueAsync(for: .medianLineVariance) < 1.6455475289674493 {
            return -1
        } else {
            if await group.decisionTreeValueAsync(for: .neighborLineRhoScore) < 0.451455666214257 {
                return -1
            } else {
                return 1
            }
        }
}

fileprivate func subtree_920E11FF_249C_4880_82B9_91A6E869F9F6(_ group: ClassifiableOutlierGroup) async -> Double {
        if group.decisionTreeValue(for: .centerX) < 0.44422786720321933 {
            return -1
        } else {
            return 1
        }
}

fileprivate func subtree_6F9CB5B3_B047_456F_9549_88223C3FC492(_ group: ClassifiableOutlierGroup) async -> Double {
        if group.decisionTreeValue(for: .centerX) < 0.31690140845070425 {
            if group.decisionTreeValue(for: .centerY) < 0.6582767722473605 {
                if group.decisionTreeValue(for: .size) < 2.245277851118779e-05 {
                    return -1
                } else {
                    return 1
                }
            } else {
                return 1
            }
        } else {
            return 1
        }
}
}