/*
   written by decision_tree_generator on 2025-01-26 16:38:10 +0000 in 0 seconds

   with training data consisting of:
     - 149 groups known to be positive
     - 2397 groups known to be negative

   from input data described by:
     - /qp/star_validated/01_26_2025-test-train

   This is tree number 1 of a forest

   This tree was NOT pruned with test data

*/

import Foundation
import StarCore

// DO NOT EDIT THIS FILE
// DO NOT EDIT THIS FILE
// DO NOT EDIT THIS FILE

public struct OutlierGroupDecisionTreeForest_52ebe851: DecisionTree {
    public init() { }
    public let sha256 = "52ebe8516a16b041d8343c8f9becb411630e88feb66aa3ca592215c1d30abd63"
    public let name = "52ebe851"
    public let sha256Prefix = "52ebe851"
    public let maxDepth = -1
    public let type: ClassifierType = .tree(DecisionTreeParams(name: "52ebe851",
                                               inputSequences:         [
            "/qp/star_validated/01_26_2025-test-train"
        ],
                                               positiveTrainingSize: 149,
                                               negativeTrainingSize: 2397,
                                               decisionTypes: [
        .size,
        .width,
        .height,
        .centerX,
        .centerY,
        .minX,
        .minY,
        .maxX,
        .maxY,
        .hypotenuse,
        .aspectRatio,
        .fillAmount,
        .surfaceAreaRatio,
        .averagebrightness,
        .medianBrightness,
        .maxBrightness,
        .numberOfNearbyOutliersInSameFrame,
        .maxHoughTransformCount,
        .pixelBorderAmount,
        .averageLineVariance,
        .medianLineVariance,
        .lineLength,
        .nearbyDirectOverlapScore,
        .boundingBoxOverlapScore,
        .lineFillAmount,
        .borderBrightness,
        .bunchCount,
        .medianBunchSize,
        .maxBunchSize,
        .neighborLineThetaScore,
        .neighborLineRhoScore,
        .neighborLineSizeScore,
        .neighborLineBrightnessScore,
        .neighborLineDistanceScore
    ]
,
                                               decisionSplitTypes: [
        .median
    ]
,
                                               maxDepth: -1,
                                               pruned: false))
    
    public let generationSecondsSince1970 = 1737909490.301153

    // the list of decision types this tree did not use
    public let notUsedDecisionTypes: [OutlierGroupFeature] = [

    ]


    // a way to call into the decision tree without an OutlierGroup object
    // it's going to blow up unless supplied with the expected set of features
    // return value is between -1 and 1, 1 is paint
    public func classification(
       of features: [OutlierGroupFeature], // parallel
       and values: [Double]                 // arrays
      ) async -> Double
    {
        let featureData = OutlierGroupFeatureData(features: features, values: values)
        return await classification(of: featureData)
    }

    // the actual tree resides here
    // return value is between -1 and 1, 1 is paint
    public func classification(of group: ClassifiableOutlierGroup) async -> Double 
    {
        if await group.decisionTreeValueAsync(for: .maxBunchSize) < 92.5 {
            if await group.decisionTreeValueAsync(for: .medianBunchSize) < 33.0 {
                if await group.decisionTreeValueAsync(for: .lineLength) < 193.48775723804465 {
                    if await group.decisionTreeValueAsync(for: .maxHoughTransformCount) < 5.855226062441265 {
                        return -1
                    } else {
                        if group.decisionTreeValue(for: .surfaceAreaRatio) < 0.9936305732484076 {
                            if await group.decisionTreeValueAsync(for: .lineLength) < 93.96504312901828 {
                                return await subtree_7E339A5C_E711_4F95_BD1C_46642A240DF3(group)
                            } else {
                                return await subtree_7A880A5F_1164_4A75_913E_CFE84C34A81E(group)
                            }
                        } else {
                            if group.decisionTreeValue(for: .fillAmount) < 0.7777777777777778 {
                                return -1
                            } else {
                                return await subtree_E638CA2D_9621_42AD_9857_0F425FC3A440(group)
                            }
                        }
                    }
                } else {
                    if await group.decisionTreeValueAsync(for: .lineLength) < 301.2252374733167 {
                        if await group.decisionTreeValueAsync(for: .maxHoughTransformCount) < 12.344307761127263 {
                            return -1
                        } else {
                            if await group.decisionTreeValueAsync(for: .borderBrightness) < 0.03546932943217773 {
                                return -1
                            } else {
                                return 1
                            }
                        }
                    } else {
                        if group.decisionTreeValue(for: .pixelBorderAmount) < 1.4348877446790769 {
                            return -1
                        } else {
                            if await group.decisionTreeValueAsync(for: .neighborLineDistanceScore) < 1.5124745511338749 {
                                return 1
                            } else {
                                return -1
                            }
                        }
                    }
                }
            } else {
                if group.decisionTreeValue(for: .height) < 0.003299396681749623 {
                    if group.decisionTreeValue(for: .centerY) < 0.8407805429864253 {
                        if group.decisionTreeValue(for: .fillAmount) < 0.35245271867612293 {
                            if await group.decisionTreeValueAsync(for: .lineFillAmount) < 7.609687396611282 {
                                return await subtree_7602F89F_B544_48A2_9A97_7C5B0F05BED3(group)
                            } else {
                                return await subtree_7C36F9B1_E785_4076_A18F_E08195091A2A(group)
                            }
                        } else {
                            if group.decisionTreeValue(for: .centerY) < 0.5786199095022625 {
                                return -1
                            } else {
                                return 1
                            }
                        }
                    } else {
                        return -1
                    }
                } else {
                    if group.decisionTreeValue(for: .maxBrightness) < 13335.0 {
                        if group.decisionTreeValue(for: .medianBrightness) < 5537.0 {
                            return -1
                        } else {
                            if group.decisionTreeValue(for: .centerX) < 0.6923415492957746 {
                                return await subtree_DFEBDD3E_BA57_49A7_AF66_DA2DF7068749(group)
                            } else {
                                return -1
                            }
                        }
                    } else {
                        if await group.decisionTreeValueAsync(for: .maxBunchSize) < 62.0 {
                            if group.decisionTreeValue(for: .minX) < 0.7076836016096579 {
                                return -1
                            } else {
                                return 1
                            }
                        } else {
                            if group.decisionTreeValue(for: .height) < 0.006221719457013575 {
                                return 1
                            } else {
                                return await subtree_F9EA05AD_7F80_4716_AEE2_28434DD0EC23(group)
                            }
                        }
                    }
                }
            }
        } else {
            if group.decisionTreeValue(for: .height) < 0.00942684766214178 {
                if group.decisionTreeValue(for: .centerY) < 0.8083521870286576 {
                    if group.decisionTreeValue(for: .averagebrightness) < 7235.0 {
                        if await group.decisionTreeValueAsync(for: .numberOfNearbyOutliersInSameFrame) < 1.5 {
                            if await group.decisionTreeValueAsync(for: .borderBrightness) < 0.03829183737787582 {
                                return await subtree_AB58A60C_DC19_46F9_99E3_EC1B311840C5(group)
                            } else {
                                return await subtree_2472A8DF_F8C0_43E5_ADBF_36C8A374CDCF(group)
                            }
                        } else {
                            if group.decisionTreeValue(for: .medianBrightness) < 4633.5 {
                                return -1
                            } else {
                                return 1
                            }
                        }
                    } else {
                        return 1
                    }
                } else {
                    if group.decisionTreeValue(for: .maxY) < 0.8428544494720965 {
                        return 1
                    } else {
                        return -1
                    }
                }
            } else {
                if group.decisionTreeValue(for: .medianBrightness) < 7554.5 {
                    if group.decisionTreeValue(for: .averagebrightness) < 6080.5 {
                        if await group.decisionTreeValueAsync(for: .numberOfNearbyOutliersInSameFrame) < 2.5 {
                            if await group.decisionTreeValueAsync(for: .borderBrightness) < 0.07504217974868424 {
                                return await subtree_EA040FEE_E468_48D7_94D3_383A9D02AABE(group)
                            } else {
                                return await subtree_CC80EB77_86AB_4E57_8131_3E6CC215765B(group)
                            }
                        } else {
                            if await group.decisionTreeValueAsync(for: .maxBunchSize) < 132.5 {
                                return 1
                            } else {
                                return -1
                            }
                        }
                    } else {
                        if await group.decisionTreeValueAsync(for: .medianBunchSize) < 91.5 {
                            if await group.decisionTreeValueAsync(for: .neighborLineBrightnessScore) < 0.6540306701643817 {
                                return await subtree_1913961D_5F35_4ADE_B9BA_A5522813C92B(group)
                            } else {
                                return await subtree_E77EC254_268D_4538_9C5D_F3F9DFAD5C47(group)
                            }
                        } else {
                            if group.decisionTreeValue(for: .pixelBorderAmount) < 0.999535784391745 {
                                return -1
                            } else {
                                return 1
                            }
                        }
                    }
                } else {
                    if group.decisionTreeValue(for: .size) < 6.5556423002570475e-06 {
                        if await group.decisionTreeValueAsync(for: .neighborLineSizeScore) < 1.456334516792979 {
                            return 1
                        } else {
                            return -1
                        }
                    } else {
                        return 1
                    }
                }
            }
        }
    }


fileprivate func subtree_7E339A5C_E711_4F95_BD1C_46642A240DF3(_ group: ClassifiableOutlierGroup) async -> Double {
        if await group.decisionTreeValueAsync(for: .medianLineVariance) < 0.5593129651739124 {
            if await group.decisionTreeValueAsync(for: .borderBrightness) < 0.04684684684684685 {
                return -1
            } else {
                if group.decisionTreeValue(for: .size) < 2.1338437867021132e-07 {
                    return 1
                } else {
                    return -1
                }
            }
        } else {
            return -1
        }
}

fileprivate func subtree_7A880A5F_1164_4A75_913E_CFE84C34A81E(_ group: ClassifiableOutlierGroup) async -> Double {
        if await group.decisionTreeValueAsync(for: .lineLength) < 173.8539848169995 {
            return -1
        } else {
            return 1
        }
}

fileprivate func subtree_E638CA2D_9621_42AD_9857_0F425FC3A440(_ group: ClassifiableOutlierGroup) async -> Double {
        if group.decisionTreeValue(for: .size) < 1.5411094015070817e-07 {
            if group.decisionTreeValue(for: .averagebrightness) < 6171.0 {
                if group.decisionTreeValue(for: .centerY) < 0.322209653092006 {
                    return -1
                } else {
                    return 1
                }
            } else {
                return -1
            }
        } else {
            return -1
        }
}

fileprivate func subtree_7602F89F_B544_48A2_9A97_7C5B0F05BED3(_ group: ClassifiableOutlierGroup) async -> Double {
        if group.decisionTreeValue(for: .averagebrightness) < 6115.5 {
            return -1
        } else {
            if group.decisionTreeValue(for: .size) < 1.1143406441666592e-06 {
                return -1
            } else {
                return 1
            }
        }
}

fileprivate func subtree_7C36F9B1_E785_4076_A18F_E08195091A2A(_ group: ClassifiableOutlierGroup) async -> Double {
        if group.decisionTreeValue(for: .width) < 0.0054703219315895375 {
            return 1
        } else {
            return -1
        }
}

fileprivate func subtree_DFEBDD3E_BA57_49A7_AF66_DA2DF7068749(_ group: ClassifiableOutlierGroup) async -> Double {
        if group.decisionTreeValue(for: .width) < 0.003206740442655936 {
            if group.decisionTreeValue(for: .fillAmount) < 0.13344941348973605 {
                return -1
            } else {
                return 1
            }
        } else {
            if group.decisionTreeValue(for: .size) < 1.7189297170655911e-06 {
                return 1
            } else {
                return -1
            }
        }
}

fileprivate func subtree_F9EA05AD_7F80_4716_AEE2_28434DD0EC23(_ group: ClassifiableOutlierGroup) async -> Double {
        if await group.decisionTreeValueAsync(for: .medianBunchSize) < 68.0 {
            return 1
        } else {
            return -1
        }
}

fileprivate func subtree_AB58A60C_DC19_46F9_99E3_EC1B311840C5(_ group: ClassifiableOutlierGroup) async -> Double {
        if await group.decisionTreeValueAsync(for: .boundingBoxOverlapScore) < 0.007197089528630181 {
            if group.decisionTreeValue(for: .averagebrightness) < 4216.5 {
                return 1
            } else {
                return -1
            }
        } else {
            if group.decisionTreeValue(for: .size) < 7.255068874787185e-06 {
                return 1
            } else {
                return -1
            }
        }
}

fileprivate func subtree_2472A8DF_F8C0_43E5_ADBF_36C8A374CDCF(_ group: ClassifiableOutlierGroup) async -> Double {
        if group.decisionTreeValue(for: .fillAmount) < 0.23483573717948716 {
            return 1
        } else {
            return -1
        }
}

fileprivate func subtree_EA040FEE_E468_48D7_94D3_383A9D02AABE(_ group: ClassifiableOutlierGroup) async -> Double {
        if group.decisionTreeValue(for: .aspectRatio) < 4.363211951447246 {
            return -1
        } else {
            return 1
        }
}

fileprivate func subtree_CC80EB77_86AB_4E57_8131_3E6CC215765B(_ group: ClassifiableOutlierGroup) async -> Double {
        if group.decisionTreeValue(for: .size) < 4.315106324219828e-06 {
            return -1
        } else {
            return 1
        }
}

fileprivate func subtree_1913961D_5F35_4ADE_B9BA_A5522813C92B(_ group: ClassifiableOutlierGroup) async -> Double {
        if await group.decisionTreeValueAsync(for: .averageLineVariance) < 4.166071507957305 {
            return 1
        } else {
            return -1
        }
}

fileprivate func subtree_E77EC254_268D_4538_9C5D_F3F9DFAD5C47(_ group: ClassifiableOutlierGroup) async -> Double {
        if await group.decisionTreeValueAsync(for: .maxHoughTransformCount) < 18.575138568596515 {
            if group.decisionTreeValue(for: .fillAmount) < 0.019093633474918624 {
                return -1
            } else {
                return 1
            }
        } else {
            if group.decisionTreeValue(for: .centerX) < 0.7366071428571428 {
                return 1
            } else {
                return -1
            }
        }
}
}