/*
   written by decision_tree_generator on 2025-01-26 16:38:10 +0000 in 0 seconds

   with training data consisting of:
     - 149 groups known to be positive
     - 2397 groups known to be negative

   from input data described by:
     - /qp/star_validated/01_26_2025-test-train

   This is tree number 2 of a forest

   This tree was NOT pruned with test data

*/

import Foundation
import StarCore

// DO NOT EDIT THIS FILE
// DO NOT EDIT THIS FILE
// DO NOT EDIT THIS FILE

public struct OutlierGroupDecisionTreeForest_333bb8d8: DecisionTree {
    public init() { }
    public let sha256 = "333bb8d894ef6ebe156c5ac2e72509fbe344d7c2e719e0d4110b6291a3aa2ad0"
    public let name = "333bb8d8"
    public let sha256Prefix = "333bb8d8"
    public let maxDepth = -1
    public let type: ClassifierType = .tree(DecisionTreeParams(name: "333bb8d8",
                                               inputSequences:         [
            "/qp/star_validated/01_26_2025-test-train"
        ],
                                               positiveTrainingSize: 149,
                                               negativeTrainingSize: 2397,
                                               decisionTypes: [
        .size,
        .width,
        .height,
        .centerX,
        .centerY,
        .minX,
        .minY,
        .maxX,
        .maxY,
        .hypotenuse,
        .aspectRatio,
        .fillAmount,
        .surfaceAreaRatio,
        .averagebrightness,
        .medianBrightness,
        .maxBrightness,
        .numberOfNearbyOutliersInSameFrame,
        .maxHoughTransformCount,
        .pixelBorderAmount,
        .averageLineVariance,
        .medianLineVariance,
        .lineLength,
        .nearbyDirectOverlapScore,
        .boundingBoxOverlapScore,
        .lineFillAmount,
        .borderBrightness,
        .bunchCount,
        .medianBunchSize,
        .maxBunchSize,
        .neighborLineThetaScore,
        .neighborLineRhoScore,
        .neighborLineSizeScore,
        .neighborLineBrightnessScore,
        .neighborLineDistanceScore
    ]
,
                                               decisionSplitTypes: [
        .median
    ]
,
                                               maxDepth: -1,
                                               pruned: false))
    
    public let generationSecondsSince1970 = 1737909490.300566

    // the list of decision types this tree did not use
    public let notUsedDecisionTypes: [OutlierGroupFeature] = [

    ]


    // a way to call into the decision tree without an OutlierGroup object
    // it's going to blow up unless supplied with the expected set of features
    // return value is between -1 and 1, 1 is paint
    public func classification(
       of features: [OutlierGroupFeature], // parallel
       and values: [Double]                 // arrays
      ) async -> Double
    {
        let featureData = OutlierGroupFeatureData(features: features, values: values)
        return await classification(of: featureData)
    }

    // the actual tree resides here
    // return value is between -1 and 1, 1 is paint
    public func classification(of group: ClassifiableOutlierGroup) async -> Double 
    {
        if await group.decisionTreeValueAsync(for: .maxBunchSize) < 85.5 {
            if await group.decisionTreeValueAsync(for: .medianBunchSize) < 32.5 {
                if await group.decisionTreeValueAsync(for: .maxBunchSize) < 35.5 {
                    if await group.decisionTreeValueAsync(for: .borderBrightness) < 0.0607712497476277 {
                        return -1
                    } else {
                        if group.decisionTreeValue(for: .fillAmount) < 0.38770604395604397 {
                            return -1
                        } else {
                            if group.decisionTreeValue(for: .width) < 0.00044014084507042255 {
                                return await subtree_D90B8F87_A3BC_4720_A5E7_6D5165F61C17(group)
                            } else {
                                return await subtree_C1C23CDD_E882_4D9B_807C_6A3ADF2713C1(group)
                            }
                        }
                    }
                } else {
                    if group.decisionTreeValue(for: .centerY) < 0.5682503770739065 {
                        if group.decisionTreeValue(for: .maxBrightness) < 14891.0 {
                            if group.decisionTreeValue(for: .surfaceAreaRatio) < 0.991733432916893 {
                                return -1
                            } else {
                                return 1
                            }
                        } else {
                            if group.decisionTreeValue(for: .aspectRatio) < 2.375438596491228 {
                                return await subtree_4493E9F7_2D2D_4B5C_979F_A77E47755BFE(group)
                            } else {
                                return 1
                            }
                        }
                    } else {
                        if group.decisionTreeValue(for: .size) < 7.764820446054911e-06 {
                            if group.decisionTreeValue(for: .centerY) < 0.7959087481146305 {
                                return await subtree_DDC50BB4_70EB_4411_A66A_D469868AF740(group)
                            } else {
                                return -1
                            }
                        } else {
                            if group.decisionTreeValue(for: .size) < 1.187839707930843e-05 {
                                return -1
                            } else {
                                return 1
                            }
                        }
                    }
                }
            } else {
                if group.decisionTreeValue(for: .height) < 0.0034879336349924587 {
                    if group.decisionTreeValue(for: .centerY) < 0.8344645550527903 {
                        if await group.decisionTreeValueAsync(for: .neighborLineSizeScore) < 0.5307692307692308 {
                            if group.decisionTreeValue(for: .fillAmount) < 0.44917184265010346 {
                                return -1
                            } else {
                                return 1
                            }
                        } else {
                            return 1
                        }
                    } else {
                        if group.decisionTreeValue(for: .centerY) < 0.8448340874811463 {
                            if group.decisionTreeValue(for: .height) < 0.0009426847662141781 {
                                return 1
                            } else {
                                return -1
                            }
                        } else {
                            return -1
                        }
                    }
                } else {
                    if group.decisionTreeValue(for: .averagebrightness) < 9814.5 {
                        if await group.decisionTreeValueAsync(for: .neighborLineRhoScore) < 0.3217476927019811 {
                            if await group.decisionTreeValueAsync(for: .averageLineVariance) < 0.5657475850923362 {
                                return await subtree_4A2C5AC3_06DA_4243_ADAE_481A3DEB65BB(group)
                            } else {
                                return -1
                            }
                        } else {
                            if group.decisionTreeValue(for: .averagebrightness) < 6662.5 {
                                return -1
                            } else {
                                return 1
                            }
                        }
                    } else {
                        if group.decisionTreeValue(for: .size) < 1.69522034165779e-06 {
                            if await group.decisionTreeValueAsync(for: .numberOfNearbyOutliersInSameFrame) < 0.5 {
                                return -1
                            } else {
                                return 1
                            }
                        } else {
                            if group.decisionTreeValue(for: .maxX) < 0.610601106639839 {
                                return -1
                            } else {
                                return 1
                            }
                        }
                    }
                }
            }
        } else {
            if group.decisionTreeValue(for: .centerY) < 0.6257541478129713 {
                if group.decisionTreeValue(for: .medianBrightness) < 7515.0 {
                    if group.decisionTreeValue(for: .averagebrightness) < 6092.5 {
                        if group.decisionTreeValue(for: .height) < 0.011312217194570135 {
                            if await group.decisionTreeValueAsync(for: .numberOfNearbyOutliersInSameFrame) < 1.5 {
                                return await subtree_C3003FD5_BD48_441F_9001_4BA565C5AED4(group)
                            } else {
                                return await subtree_7D3D0775_8CDD_43DC_A48D_33159573F322(group)
                            }
                        } else {
                            if group.decisionTreeValue(for: .maxBrightness) < 16765.5 {
                                return await subtree_682B9A19_7ABC_48EB_B7E5_5449A76961E8(group)
                            } else {
                                return await subtree_5C6D2C63_21B5_400C_BDC7_B7B817C13A49(group)
                            }
                        }
                    } else {
                        if await group.decisionTreeValueAsync(for: .lineFillAmount) < 25.13611480136649 {
                            if await group.decisionTreeValueAsync(for: .maxBunchSize) < 167.5 {
                                return await subtree_483718F1_7E7E_4B10_807B_9F89B2A1DA4A(group)
                            } else {
                                return await subtree_F6FA1F21_A882_4169_A24D_03CB18FE2946(group)
                            }
                        } else {
                            if await group.decisionTreeValueAsync(for: .bunchCount) < 23.0 {
                                return 1
                            } else {
                                return -1
                            }
                        }
                    }
                } else {
                    if await group.decisionTreeValueAsync(for: .lineLength) < 43.12309541019092 {
                        return -1
                    } else {
                        return 1
                    }
                }
            } else {
                if group.decisionTreeValue(for: .centerY) < 0.8231523378582202 {
                    if group.decisionTreeValue(for: .aspectRatio) < 1.46875 {
                        if group.decisionTreeValue(for: .medianBrightness) < 7689.0 {
                            if group.decisionTreeValue(for: .averagebrightness) < 6261.0 {
                                return -1
                            } else {
                                return await subtree_F617F8C8_9B8A_48F7_B668_44323E7843E7(group)
                            }
                        } else {
                            return 1
                        }
                    } else {
                        return 1
                    }
                } else {
                    if group.decisionTreeValue(for: .minY) < 0.8409690799396682 {
                        return 1
                    } else {
                        return -1
                    }
                }
            }
        }
    }


fileprivate func subtree_D90B8F87_A3BC_4720_A5E7_6D5165F61C17(_ group: ClassifiableOutlierGroup) async -> Double {
        if group.decisionTreeValue(for: .aspectRatio) < 1.05 {
            if group.decisionTreeValue(for: .height) < 0.0010369532428355958 {
                return -1
            } else {
                if await group.decisionTreeValueAsync(for: .numberOfNearbyOutliersInSameFrame) < 3.5 {
                    return -1
                } else {
                    return 1
                }
            }
        } else {
            return 1
        }
}

fileprivate func subtree_C1C23CDD_E882_4D9B_807C_6A3ADF2713C1(_ group: ClassifiableOutlierGroup) async -> Double {
        if await group.decisionTreeValueAsync(for: .boundingBoxOverlapScore) < 0.041666666666666664 {
            return -1
        } else {
            if group.decisionTreeValue(for: .surfaceAreaRatio) < 0.8958333333333333 {
                return 1
            } else {
                return -1
            }
        }
}

fileprivate func subtree_4493E9F7_2D2D_4B5C_979F_A77E47755BFE(_ group: ClassifiableOutlierGroup) async -> Double {
        if await group.decisionTreeValueAsync(for: .neighborLineDistanceScore) < 0.5249885294786345 {
            return -1
        } else {
            return 1
        }
}

fileprivate func subtree_DDC50BB4_70EB_4411_A66A_D469868AF740(_ group: ClassifiableOutlierGroup) async -> Double {
        if await group.decisionTreeValueAsync(for: .medianBunchSize) < 21.5 {
            return -1
        } else {
            return 1
        }
}

fileprivate func subtree_4A2C5AC3_06DA_4243_ADAE_481A3DEB65BB(_ group: ClassifiableOutlierGroup) async -> Double {
        if group.decisionTreeValue(for: .centerX) < 0.6063883299798793 {
            if group.decisionTreeValue(for: .maxX) < 0.46478873239436624 {
                return -1
            } else {
                return 1
            }
        } else {
            return -1
        }
}

fileprivate func subtree_C3003FD5_BD48_441F_9001_4BA565C5AED4(_ group: ClassifiableOutlierGroup) async -> Double {
        if group.decisionTreeValue(for: .pixelBorderAmount) < 1.6094937134404625 {
            return -1
        } else {
            return 1
        }
}

fileprivate func subtree_7D3D0775_8CDD_43DC_A48D_33159573F322(_ group: ClassifiableOutlierGroup) async -> Double {
        if group.decisionTreeValue(for: .averagebrightness) < 4839.0 {
            return -1
        } else {
            return 1
        }
}

fileprivate func subtree_682B9A19_7ABC_48EB_B7E5_5449A76961E8(_ group: ClassifiableOutlierGroup) async -> Double {
        if await group.decisionTreeValueAsync(for: .medianLineVariance) < 1.6833938183337636 {
            return -1
        } else {
            if group.decisionTreeValue(for: .maxBrightness) < 11745.0 {
                return 1
            } else {
                return -1
            }
        }
}

fileprivate func subtree_5C6D2C63_21B5_400C_BDC7_B7B817C13A49(_ group: ClassifiableOutlierGroup) async -> Double {
        if group.decisionTreeValue(for: .size) < 2.2002300378439567e-05 {
            return -1
        } else {
            return 1
        }
}

fileprivate func subtree_483718F1_7E7E_4B10_807B_9F89B2A1DA4A(_ group: ClassifiableOutlierGroup) async -> Double {
        if group.decisionTreeValue(for: .maxY) < 0.5782428355957767 {
            return -1
        } else {
            return 1
        }
}

fileprivate func subtree_F6FA1F21_A882_4169_A24D_03CB18FE2946(_ group: ClassifiableOutlierGroup) async -> Double {
        if group.decisionTreeValue(for: .size) < 6.520078237145346e-06 {
            return 1
        } else {
            if group.decisionTreeValue(for: .maxY) < 0.5436463046757165 {
                if group.decisionTreeValue(for: .size) < 7.255068874787185e-06 {
                    return 1
                } else {
                    return -1
                }
            } else {
                return 1
            }
        }
}

fileprivate func subtree_F617F8C8_9B8A_48F7_B668_44323E7843E7(_ group: ClassifiableOutlierGroup) async -> Double {
        if group.decisionTreeValue(for: .minY) < 0.6616704374057315 {
            return -1
        } else {
            return 1
        }
}
}