/*
   written by decision_tree_generator on 2025-01-26 16:38:10 +0000 in 0 seconds

   with training data consisting of:
     - 150 groups known to be positive
     - 2398 groups known to be negative

   from input data described by:
     - /qp/star_validated/01_26_2025-test-train

   This is tree number 7 of a forest

   This tree was NOT pruned with test data

*/

import Foundation
import StarCore

// DO NOT EDIT THIS FILE
// DO NOT EDIT THIS FILE
// DO NOT EDIT THIS FILE

public struct OutlierGroupDecisionTreeForest_e5790f28: DecisionTree {
    public init() { }
    public let sha256 = "e5790f28fb639056bdcc94ed488abb2312444f790bf9112fdc7866964bae5788"
    public let name = "e5790f28"
    public let sha256Prefix = "e5790f28"
    public let maxDepth = -1
    public let type: ClassifierType = .tree(DecisionTreeParams(name: "e5790f28",
                                               inputSequences:         [
            "/qp/star_validated/01_26_2025-test-train"
        ],
                                               positiveTrainingSize: 150,
                                               negativeTrainingSize: 2398,
                                               decisionTypes: [
        .size,
        .width,
        .height,
        .centerX,
        .centerY,
        .minX,
        .minY,
        .maxX,
        .maxY,
        .hypotenuse,
        .aspectRatio,
        .fillAmount,
        .surfaceAreaRatio,
        .averagebrightness,
        .medianBrightness,
        .maxBrightness,
        .numberOfNearbyOutliersInSameFrame,
        .maxHoughTransformCount,
        .pixelBorderAmount,
        .averageLineVariance,
        .medianLineVariance,
        .lineLength,
        .nearbyDirectOverlapScore,
        .boundingBoxOverlapScore,
        .lineFillAmount,
        .borderBrightness,
        .bunchCount,
        .medianBunchSize,
        .maxBunchSize,
        .neighborLineThetaScore,
        .neighborLineRhoScore,
        .neighborLineSizeScore,
        .neighborLineBrightnessScore,
        .neighborLineDistanceScore
    ]
,
                                               decisionSplitTypes: [
        .median
    ]
,
                                               maxDepth: -1,
                                               pruned: false))
    
    public let generationSecondsSince1970 = 1737909490.3021312

    // the list of decision types this tree did not use
    public let notUsedDecisionTypes: [OutlierGroupFeature] = [

    ]


    // a way to call into the decision tree without an OutlierGroup object
    // it's going to blow up unless supplied with the expected set of features
    // return value is between -1 and 1, 1 is paint
    public func classification(
       of features: [OutlierGroupFeature], // parallel
       and values: [Double]                 // arrays
      ) async -> Double
    {
        let featureData = OutlierGroupFeatureData(features: features, values: values)
        return await classification(of: featureData)
    }

    // the actual tree resides here
    // return value is between -1 and 1, 1 is paint
    public func classification(of group: ClassifiableOutlierGroup) async -> Double 
    {
        if await group.decisionTreeValueAsync(for: .maxBunchSize) < 92.5 {
            if await group.decisionTreeValueAsync(for: .medianBunchSize) < 33.0 {
                if await group.decisionTreeValueAsync(for: .maxBunchSize) < 35.5 {
                    if group.decisionTreeValue(for: .fillAmount) < 0.5045454545454545 {
                        return -1
                    } else {
                        if group.decisionTreeValue(for: .height) < 0.0008484162895927602 {
                            if group.decisionTreeValue(for: .fillAmount) < 0.8333333333333333 {
                                return -1
                            } else {
                                return await subtree_7CE1D1DE_D422_46D8_97A2_D7F4EF5191F4(group)
                            }
                        } else {
                            if group.decisionTreeValue(for: .height) < 0.0010369532428355958 {
                                return -1
                            } else {
                                return await subtree_AC5EBB9A_37B3_44A8_8119_387FADDBF6C3(group)
                            }
                        }
                    }
                } else {
                    if group.decisionTreeValue(for: .centerY) < 0.5678733031674208 {
                        if group.decisionTreeValue(for: .maxBrightness) < 15976.5 {
                            if await group.decisionTreeValueAsync(for: .maxHoughTransformCount) < 12.804036267914594 {
                                return -1
                            } else {
                                return await subtree_2F29E185_B92E_4C42_A308_71E70799D988(group)
                            }
                        } else {
                            if group.decisionTreeValue(for: .aspectRatio) < 2.375438596491228 {
                                return await subtree_2F1ABA75_DB52_4A4B_917F_D5A68FE88049(group)
                            } else {
                                return 1
                            }
                        }
                    } else {
                        if group.decisionTreeValue(for: .size) < 7.764820446054911e-06 {
                            if group.decisionTreeValue(for: .centerY) < 0.7959087481146305 {
                                return await subtree_ECC08F25_1EC2_4BAC_8F6A_89D8554C3FFB(group)
                            } else {
                                return -1
                            }
                        } else {
                            if group.decisionTreeValue(for: .size) < 1.1985089268643534e-05 {
                                return -1
                            } else {
                                return 1
                            }
                        }
                    }
                }
            } else {
                if group.decisionTreeValue(for: .height) < 0.003205128205128205 {
                    if group.decisionTreeValue(for: .centerY) < 0.8321078431372548 {
                        if group.decisionTreeValue(for: .centerY) < 0.6512066365007542 {
                            if group.decisionTreeValue(for: .fillAmount) < 0.44917184265010346 {
                                return -1
                            } else {
                                return 1
                            }
                        } else {
                            return 1
                        }
                    } else {
                        if group.decisionTreeValue(for: .maxY) < 0.8455882352941176 {
                            if await group.decisionTreeValueAsync(for: .lineLength) < 37.73951288797381 {
                                return 1
                            } else {
                                return -1
                            }
                        } else {
                            return -1
                        }
                    }
                } else {
                    if await group.decisionTreeValueAsync(for: .neighborLineRhoScore) < 0.33350695283551884 {
                        if group.decisionTreeValue(for: .medianBrightness) < 10470.0 {
                            if await group.decisionTreeValueAsync(for: .averageLineVariance) < 0.5575553832216265 {
                                return await subtree_5E35AE50_B75C_4379_818D_B66FEFB37A40(group)
                            } else {
                                return -1
                            }
                        } else {
                            if await group.decisionTreeValueAsync(for: .bunchCount) < 1.5 {
                                return 1
                            } else {
                                return -1
                            }
                        }
                    } else {
                        if group.decisionTreeValue(for: .surfaceAreaRatio) < 0.9609375 {
                            if await group.decisionTreeValueAsync(for: .borderBrightness) < 0.03519551116518877 {
                                return 1
                            } else {
                                return -1
                            }
                        } else {
                            if await group.decisionTreeValueAsync(for: .averageLineVariance) < 0.761053661111919 {
                                return await subtree_CEFD4690_7898_4896_AB2A_8693D08D9B02(group)
                            } else {
                                return -1
                            }
                        }
                    }
                }
            }
        } else {
            if group.decisionTreeValue(for: .maxY) < 0.6355580693815988 {
                if group.decisionTreeValue(for: .averagebrightness) < 7739.0 {
                    if group.decisionTreeValue(for: .averagebrightness) < 6065.0 {
                        if await group.decisionTreeValueAsync(for: .numberOfNearbyOutliersInSameFrame) < 1.5 {
                            if await group.decisionTreeValueAsync(for: .borderBrightness) < 0.04452658202924233 {
                                return await subtree_29E219E4_67AC_475A_B7C0_7B1720CF14B4(group)
                            } else {
                                return await subtree_8B72430E_D3AC_4282_BA0E_527532ACC66C(group)
                            }
                        } else {
                            if group.decisionTreeValue(for: .aspectRatio) < 1.7058823529411764 {
                                return await subtree_74985E77_64A2_4E55_A55E_9F53C4B2E260(group)
                            } else {
                                return 1
                            }
                        }
                    } else {
                        if await group.decisionTreeValueAsync(for: .lineFillAmount) < 24.280331701506196 {
                            if await group.decisionTreeValueAsync(for: .borderBrightness) < 0.02930753696827568 {
                                return await subtree_F3826570_B86D_4DB1_A18B_40BF77D701D1(group)
                            } else {
                                return await subtree_CB020870_B6FA_4751_A2A0_F3FE26E3BAA8(group)
                            }
                        } else {
                            if group.decisionTreeValue(for: .width) < 0.05790995975855131 {
                                return 1
                            } else {
                                return await subtree_F3F3B574_4A5D_4889_AC0C_95DF78265CA2(group)
                            }
                        }
                    }
                } else {
                    return 1
                }
            } else {
                if group.decisionTreeValue(for: .centerY) < 0.8223039215686274 {
                    if group.decisionTreeValue(for: .aspectRatio) < 1.443351691581432 {
                        if group.decisionTreeValue(for: .averagebrightness) < 6870.0 {
                            if await group.decisionTreeValueAsync(for: .borderBrightness) < 0.09327448507776376 {
                                return -1
                            } else {
                                return 1
                            }
                        } else {
                            if await group.decisionTreeValueAsync(for: .neighborLineSizeScore) < 1.648760980726367 {
                                return 1
                            } else {
                                return -1
                            }
                        }
                    } else {
                        return 1
                    }
                } else {
                    if group.decisionTreeValue(for: .maxY) < 0.8428544494720965 {
                        return 1
                    } else {
                        return -1
                    }
                }
            }
        }
    }


fileprivate func subtree_7CE1D1DE_D422_46D8_97A2_D7F4EF5191F4(_ group: ClassifiableOutlierGroup) async -> Double {
        if group.decisionTreeValue(for: .size) < 1.5411094015070817e-07 {
            if group.decisionTreeValue(for: .averagebrightness) < 6171.0 {
                if group.decisionTreeValue(for: .centerY) < 0.366421568627451 {
                    return -1
                } else {
                    return 1
                }
            } else {
                return -1
            }
        } else {
            return -1
        }
}

fileprivate func subtree_AC5EBB9A_37B3_44A8_8119_387FADDBF6C3(_ group: ClassifiableOutlierGroup) async -> Double {
        if await group.decisionTreeValueAsync(for: .numberOfNearbyOutliersInSameFrame) < 3.5 {
            return -1
        } else {
            return 1
        }
}

fileprivate func subtree_2F29E185_B92E_4C42_A308_71E70799D988(_ group: ClassifiableOutlierGroup) async -> Double {
        if group.decisionTreeValue(for: .maxY) < 0.44042232277526394 {
            return -1
        } else {
            return 1
        }
}

fileprivate func subtree_2F1ABA75_DB52_4A4B_917F_D5A68FE88049(_ group: ClassifiableOutlierGroup) async -> Double {
        if group.decisionTreeValue(for: .averagebrightness) < 7155.5 {
            if await group.decisionTreeValueAsync(for: .boundingBoxOverlapScore) < 0.0036386607275409565 {
                return -1
            } else {
                return 1
            }
        } else {
            return 1
        }
}

fileprivate func subtree_ECC08F25_1EC2_4BAC_8F6A_89D8554C3FFB(_ group: ClassifiableOutlierGroup) async -> Double {
        if await group.decisionTreeValueAsync(for: .medianBunchSize) < 21.5 {
            return -1
        } else {
            return 1
        }
}

fileprivate func subtree_5E35AE50_B75C_4379_818D_B66FEFB37A40(_ group: ClassifiableOutlierGroup) async -> Double {
        if group.decisionTreeValue(for: .centerX) < 0.6421654929577465 {
            if group.decisionTreeValue(for: .pixelBorderAmount) < 1.9722222222222223 {
                return 1
            } else {
                return -1
            }
        } else {
            return -1
        }
}

fileprivate func subtree_CEFD4690_7898_4896_AB2A_8693D08D9B02(_ group: ClassifiableOutlierGroup) async -> Double {
        if await group.decisionTreeValueAsync(for: .numberOfNearbyOutliersInSameFrame) < 1.5 {
            return 1
        } else {
            return -1
        }
}

fileprivate func subtree_29E219E4_67AC_475A_B7C0_7B1720CF14B4(_ group: ClassifiableOutlierGroup) async -> Double {
        if group.decisionTreeValue(for: .medianBrightness) < 3814.5 {
            return 1
        } else {
            return -1
        }
}

fileprivate func subtree_8B72430E_D3AC_4282_BA0E_527532ACC66C(_ group: ClassifiableOutlierGroup) async -> Double {
        if await group.decisionTreeValueAsync(for: .maxHoughTransformCount) < 8.762586206896552 {
            if await group.decisionTreeValueAsync(for: .neighborLineDistanceScore) < 0.026852414677566973 {
                return -1
            } else {
                return 1
            }
        } else {
            return 1
        }
}

fileprivate func subtree_74985E77_64A2_4E55_A55E_9F53C4B2E260(_ group: ClassifiableOutlierGroup) async -> Double {
        if await group.decisionTreeValueAsync(for: .numberOfNearbyOutliersInSameFrame) < 10.0 {
            return -1
        } else {
            return 1
        }
}

fileprivate func subtree_F3826570_B86D_4DB1_A18B_40BF77D701D1(_ group: ClassifiableOutlierGroup) async -> Double {
        if await group.decisionTreeValueAsync(for: .nearbyDirectOverlapScore) < 0.07540983606557378 {
            return 1
        } else {
            return -1
        }
}

fileprivate func subtree_CB020870_B6FA_4751_A2A0_F3FE26E3BAA8(_ group: ClassifiableOutlierGroup) async -> Double {
        if group.decisionTreeValue(for: .maxY) < 0.5782428355957767 {
            return -1
        } else {
            return 1
        }
}

fileprivate func subtree_F3F3B574_4A5D_4889_AC0C_95DF78265CA2(_ group: ClassifiableOutlierGroup) async -> Double {
        if group.decisionTreeValue(for: .medianBrightness) < 6688.5 {
            return -1
        } else {
            return 1
        }
}
}