#include <libavformat/avformat.h>
#include <libavcodec/avcodec.h>
#include <stdio.h>
#include <string.h>
#include <ctype.h>
#include <stdlib.h>

// Max number of muxers to track duplicates (adjust if needed)
#define MAX_MUXERS 1024

static const char *excluded_codecs[] = {
    "vnull",
    "anull",
    "libfdk_aac",
    "hdr",
    "wbmp",
    NULL // sentinel
};


int is_excluded(const char *name) {
    for (int i = 0; excluded_codecs[i] != NULL; i++) {
        if (strcmp(name, excluded_codecs[i]) == 0) {
            return 1; // found in exclusion list
        }
    }
    return 0;
}


// Helper: make Swift-safe enum case names
void print_swift_case_name(const char *name) {
    // If first char is not alpha or '_', prefix underscore
    if (!isalpha(name[0]) && name[0] != '_') {
        putchar('_');
    }

    // Print chars, replacing '-' with '_'
    for (int i = 0; name[i] != '\0'; i++) {
        if (name[i] == '-') {
            putchar('_');
        } else {
            putchar(name[i]);
        }
    }
}

// Check if muxer name is already in the list
int already_seen(const char *name, char **seen_names, int count) {
    for (int i = 0; i < count; i++) {
        if (strcmp(name, seen_names[i]) == 0) {
            return 1;
        }
    }
    return 0;
}

// Print string escaping " characters for Swift
void print_escaped_string(const char *str) {
    while (*str) {
        if (*str == '"') {
            printf("\\\"");
        } else {
            putchar(*str);
        }
        str++;
    }
}


char *replace_comma_with_comma_dot(const char *input) {
    if (!input) return NULL;

    size_t len = strlen(input);
    // Worst case: every char is ',' so output size doubles (+1 for \0)
    size_t max_len = len * 2 + 1;
    char *output = malloc(max_len);
    if (!output) return NULL;

    size_t j = 0;
    for (size_t i = 0; i < len; i++) {
        if (input[i] == ',') {
            output[j++] = ',';
            output[j++] = '.';
        } else {
            output[j++] = input[i];
        }
    }
    output[j] = '\0';

    return output;
}

int main(void) {
    void *muxer_iter = NULL;
    const AVOutputFormat *ofmt = NULL;

    void *codec_iter = NULL;
    const AVCodec *codec = NULL;

    char *seen_muxers[MAX_MUXERS];
    int seen_count = 0;

    printf("import Foundation\n\n");
    printf("// Auto Generated by muxer_codecs.c\n\n");
    printf("// DO NOT EDIT BY HAND\n");
    printf("// DO NOT EDIT BY HAND\n");
    printf("// DO NOT EDIT BY HAND\n\n");
    printf("public enum FFmpegMuxer: String, CaseIterable, Codable, Sendable {\n");

    // Enum cases
    while ((ofmt = av_muxer_iterate(&muxer_iter))) {
        if (already_seen(ofmt->name, seen_muxers, seen_count)) {
            continue;
        }
        if (seen_count >= MAX_MUXERS) {
            fprintf(stderr, "Too many muxers, increase MAX_MUXERS\n");
            break;
        }
        seen_muxers[seen_count++] = strdup(ofmt->name);

        printf("    case ");
        print_swift_case_name(ofmt->name);
        if (strcmp(ofmt->name, "") != 0) {
            int needs_quote = 0;
            char safe_name[256];
            snprintf(safe_name, sizeof(safe_name), "%s", ofmt->name);
            if (!isalpha(safe_name[0]) && safe_name[0] != '_') {
                needs_quote = 1;
            }
            if (needs_quote) {
                printf(" = \"%s\"", ofmt->name);
            }
        }
        printf("\n");
    }
    printf("\n");

    // Description property
    printf("    public var description: String {\n");
    printf("        switch self {\n");

    for (int i = 0; i < seen_count; i++) {
        printf("        case .");
        print_swift_case_name(replace_comma_with_comma_dot(seen_muxers[i]));
        printf(":\n            return \"");
        // Find AVOutputFormat for this muxer to print long_name
        muxer_iter = NULL;
        while ((ofmt = av_muxer_iterate(&muxer_iter))) {
            if (strcmp(ofmt->name, seen_muxers[i]) == 0) {
                if (ofmt->long_name) {
                    print_escaped_string(ofmt->long_name);
                } else {
                    printf("N/A");
                }
                break;
            }
        }
        printf("\"\n");
    }

    printf("        }\n    }\n\n");

    // Supported codecs property
    printf("    public var supportedEncoders: [FFmpegEncoder] {\n");
    printf("        switch self {\n");

    for (int i = 0; i < seen_count; i++) {
        printf("        case .");
        print_swift_case_name(replace_comma_with_comma_dot(seen_muxers[i]));
        printf(":\n            return [");

        muxer_iter = NULL;
        while ((ofmt = av_muxer_iterate(&muxer_iter))) {
            if (strcmp(ofmt->name, seen_muxers[i]) == 0) {
                int first = 1;
                codec_iter = NULL;
                while ((codec = av_codec_iterate(&codec_iter))) {
                    if (!av_codec_is_encoder(codec))
                        continue;
		    
                    if(!is_excluded(codec->name) && avformat_query_codec(ofmt, codec->id, 1)) {
                        if (!first) printf(", ");
                        printf(".");
                        print_swift_case_name(codec->name);
                        first = 0;
                    }
                }
                break;
            }
        }

        printf("]\n");
    }

    printf("        }\n    }\n");

    printf("}\n");

    // Cleanup strdup memory
    for (int i = 0; i < seen_count; i++) {
        free(seen_muxers[i]);
    }

    return 0;
}
