#include <libavformat/avformat.h>
#include <libavcodec/avcodec.h>
#include <stdio.h>
#include <string.h>
#include <ctype.h>
#include <stdlib.h>

#define MAX_MUXERS 1024

static const char *excluded_codecs[] = {
    "vnull",
    "anull",
    "libfdk_aac",
    "hdr",
    "wbmp",
    NULL
};

int is_excluded(const char *name) {
    for (int i = 0; excluded_codecs[i] != NULL; i++) {
        if (strcmp(name, excluded_codecs[i]) == 0) {
            return 1;
        }
    }
    return 0;
}

void print_swift_case_name(const char *name) {
    if (!isalpha(name[0]) && name[0] != '_') {
        putchar('_');
    }
    for (int i = 0; name[i] != '\0'; i++) {
        if (name[i] == '-') {
            putchar('_');
        } else {
            putchar(name[i]);
        }
    }
}

int already_seen(const char *name, char **seen_names, int count) {
    for (int i = 0; i < count; i++) {
        if (strcmp(name, seen_names[i]) == 0) {
            return 1;
        }
    }
    return 0;
}

void print_escaped_string(const char *str) {
    while (*str) {
        if (*str == '"') {
            printf("\\\"");
        } else {
            putchar(*str);
        }
        str++;
    }
}

char *replace_comma_with_comma_dot(const char *input) {
    if (!input) return NULL;
    size_t len = strlen(input);
    size_t max_len = len * 2 + 1;
    char *output = malloc(max_len);
    if (!output) return NULL;
    size_t j = 0;
    for (size_t i = 0; i < len; i++) {
        if (input[i] == ',') {
            output[j++] = ',';
            output[j++] = '.';
        } else {
            output[j++] = input[i];
        }
    }
    output[j] = '\0';
    return output;
}

int main(void) {
    void *muxer_iter = NULL;
    const AVOutputFormat *ofmt = NULL;
    void *codec_iter = NULL;
    const AVCodec *codec = NULL;
    char *seen_muxers[MAX_MUXERS];
    int seen_count = 0;

    printf("import Foundation\n\n");
    printf("// Auto Generated by muxer_codecs.c\n\n");
    printf("public enum FFmpegMuxer: String, CaseIterable, Codable, Sendable {\n");

    // Enum cases
    while ((ofmt = av_muxer_iterate(&muxer_iter))) {
        if (already_seen(ofmt->name, seen_muxers, seen_count)) continue;
        if (seen_count >= MAX_MUXERS) {
            fprintf(stderr, "Too many muxers, increase MAX_MUXERS\n");
            break;
        }
        seen_muxers[seen_count++] = strdup(ofmt->name);

        printf("    case ");
        print_swift_case_name(ofmt->name);
        int needs_quote = (!isalpha(ofmt->name[0]) && ofmt->name[0] != '_');
        if (needs_quote) {
            printf(" = \"%s\"", ofmt->name);
        }
        printf("\n");
    }
    printf("\n");

    // Description
    printf("    public var description: String {\n        switch self {\n");
    for (int i = 0; i < seen_count; i++) {
        char *safe_name = replace_comma_with_comma_dot(seen_muxers[i]);
        printf("        case .");
        print_swift_case_name(safe_name);
        free(safe_name);
        printf(":\n            return \"");
        muxer_iter = NULL;
        while ((ofmt = av_muxer_iterate(&muxer_iter))) {
            if (strcmp(ofmt->name, seen_muxers[i]) == 0) {
                if (ofmt->long_name) {
                    print_escaped_string(ofmt->long_name);
                } else {
                    printf("N/A");
                }
                break;
            }
        }
        printf("\"\n");
    }
    printf("        }\n    }\n\n");

    // Supported Encoders
    printf("    public var supportedEncoders: [FFmpegEncoder] {\n        switch self {\n");
    for (int i = 0; i < seen_count; i++) {
        char *safe_name = replace_comma_with_comma_dot(seen_muxers[i]);
        printf("        case .");
        print_swift_case_name(safe_name);
        free(safe_name);
        printf(":\n            return [");
        muxer_iter = NULL;
        while ((ofmt = av_muxer_iterate(&muxer_iter))) {
            if (strcmp(ofmt->name, seen_muxers[i]) == 0) {
                int first = 1;
                codec_iter = NULL;
                while ((codec = av_codec_iterate(&codec_iter))) {
                    if (!av_codec_is_encoder(codec)) continue;
                    if (!is_excluded(codec->name) && avformat_query_codec(ofmt, codec->id, 1)) {
                        if (!first) printf(", ");
                        printf(".");
                        print_swift_case_name(codec->name);
                        first = 0;
                    }
                }
                break;
            }
        }
        printf("]\n");
    }
    printf("        }\n    }\n\n");

    // Default file extension property
    printf("    public var defaultFileExtension: String? {\n        switch self {\n");
    for (int i = 0; i < seen_count; i++) {
        char *safe_name = replace_comma_with_comma_dot(seen_muxers[i]);
        printf("        case .");
        print_swift_case_name(safe_name);
        free(safe_name);
        printf(":\n            return ");
        muxer_iter = NULL;
        const char *ext = NULL;
        while ((ofmt = av_muxer_iterate(&muxer_iter))) {
            if (strcmp(ofmt->name, seen_muxers[i]) == 0) {
                if (ofmt->extensions && strlen(ofmt->extensions) > 0) {
                    // Take first extension before comma
                    char ext_buf[64];
                    strncpy(ext_buf, ofmt->extensions, sizeof(ext_buf));
                    ext_buf[sizeof(ext_buf) - 1] = '\0';
                    char *comma = strchr(ext_buf, ',');
                    if (comma) *comma = '\0';
                    printf("\"%s\"\n", ext_buf);
                } else {
                    printf("nil\n");
                }
                break;
            }
        }
    }
    printf("        }\n    }\n");

    printf("}\n");

    for (int i = 0; i < seen_count; i++) {
        free(seen_muxers[i]);
    }
    return 0;
}
